GCP: modify awc module
Signed-off-by: Qi Dang <qidang@hp.com>

diff --git a/modules/gcp/awc-regional/awc-provisioning.sh.tmpl b/modules/gcp/awc-regional/awc-provisioning.sh.tmpl
--- a/modules/gcp/awc-regional/awc-provisioning.sh.tmpl
+++ b/modules/gcp/awc-regional/awc-provisioning.sh.tmpl
@@ -1,4 +1,4 @@
-# Copyright Teradici Corporation 2019-2021;  © Copyright 2022 HP Development Company, L.P.
+# © Copyright 2022 HP Development Company, L.P.
 #
 # This source code is licensed under the MIT license found in the
 # LICENSE file in the root directory of this source tree.
@@ -8,39 +8,34 @@
 ##### Template Variables #####
 AD_SERVICE_ACCOUNT_PASSWORD=${ad_service_account_password}
 AD_SERVICE_ACCOUNT_USERNAME=${ad_service_account_username}
+AWC_EXTRA_INSTALL_FLAGS=${awc_extra_install_flags}
 BUCKET_NAME=${bucket_name}
-CAC_EXTRA_INSTALL_FLAGS=${cac_extra_install_flags}
-CAC_VERSION=${cac_version}
 CAS_MGR_DEPLOYMENT_SA_FILE=${cas_mgr_deployment_sa_file}
 CAS_MGR_INSECURE=${cas_mgr_insecure}
 CAS_MGR_SCRIPT=${cas_mgr_script}
 CAS_MGR_URL=${cas_mgr_url}
+COMPUTERS_DN=${computers_dn}
 DOMAIN_CONTROLLER_IP=${domain_controller_ip}
 DOMAIN_NAME=${domain_name}
 EXTERNAL_PCOIP_IP=${external_pcoip_ip}
 GCP_OPS_AGENT_ENABLE=${gcp_ops_agent_enable}
 KMS_CRYPTOKEY_ID=${kms_cryptokey_id}
+LDAPS_CERT_FILENAME=${ldaps_cert_filename}
 OPS_SETUP_SCRIPT=${ops_setup_script}
-SSL_CERT=${ssl_cert}
-SSL_KEY=${ssl_key}
+TLS_CERT=${tls_cert}
+TLS_KEY=${tls_key}
 TERADICI_DOWNLOAD_TOKEN=${teradici_download_token}
+USERS_DN=${users_dn}
 
+AWC_BIN_PATH="/usr/local/bin/cas-connector"
+AWC_REPO_SETUP_SCRIPT_URL="https://dl.teradici.com/$TERADICI_DOWNLOAD_TOKEN/cas-manager-beta/cfg/setup/bash.rpm.sh"
+AWC_INSTALL_LOG="/var/log/teradici/awc-install.log"
+AWC_TOKEN_FILE=$PROVISIONING_DIR/connector_token
 LOG_FILE="/var/log/teradici/provisioning.log"
 PROVISIONING_DIR="/root"
 
-CAC_BIN_PATH="/usr/sbin/cloud-access-connector"
-CAC_FILENAME="cloud-access-connector_$CAC_VERSION_Linux.tar.gz"
-CAC_INSTALL_LOG="/var/log/teradici/cac-install.log"
-CAC_LOCATION_URL="https://dl.teradici.com/$TERADICI_DOWNLOAD_TOKEN/cloud-access-connector/raw/names/cloud-access-connector-linux-tgz/versions/$CAC_VERSION"
-CAC_TOKEN_FILE=$PROVISIONING_DIR/cac_token
-cd $PROVISIONING_DIR
-
 METADATA_BASE_URI="http://metadata.google.internal/computeMetadata/v1/instance"
 METADATA_AUTH_URI="$METADATA_BASE_URI/service-accounts/default/token"
-
-PCOIP_NETWORK_CONF_FILE="/etc/sysctl.d/01-pcoip-cac-network.conf"
-
-export DEBIAN_FRONTEND=noninteractive
 
 log() {
     local message="$1"
@@ -73,9 +68,18 @@ retry() {
 }
 
 install_prereqs() {
-    log "--> Installing dos2unix, python3..."
-    apt-get -qq update
-    apt install -y dos2unix python3
+    log "--> Installing dos2unix, python3, firewalld..."
+    dnf update -y
+    dnf install -y dos2unix python3 firewalld
+
+    if [ $? -ne 0 ]
+    then
+        log "--> ERROR: Failed to install prerequisites. Exiting provisioning script..."
+        exit 1
+    fi
+
+    # install requirement for get-connector-token
+    pip3 install requests
 
     if [ $? -ne 0 ]
     then
@@ -94,7 +98,7 @@ setup_ops() {
         retry 25 `# 25 retries` \
               5  `# 5s interval` \
               "gsutil cp gs://$BUCKET_NAME/$OPS_SETUP_SCRIPT ." \
-              "--> ERROR: Failed to download Logging Agent from bucket $BUCKET_NAME."
+              "--> ERROR: Failed to download Logging Agent from gs://$BUCKET_NAME/$OPS_SETUP_SCRIPT."
 
         if [ $? -ne 0 ]; then
             log "--> ERROR: Failed to install GCP OPs Agent."
@@ -105,15 +109,15 @@ setup_ops() {
         . $OPS_SETUP_SCRIPT \
             $LOG_FILE \
             "/var/log/cloud-init-output.log" \
-            "/var/log/syslog" \
-            "/var/log/teradici/cac-install.log"
+            "/var/log/messages" \
+            "$AWC_INSTALL_LOG"
     fi
 }
 
 get_credentials() {
     # In some cases, the CAS Manager Deployment Service Account key is
     # generated by a new CAS Manager VM that is being created in parallel as the
-    # CAC. Loop until the file is found in the storage bucket.
+    # AWC. Loop until the file is found in the storage bucket.
 
     retry 120 `# 120 retries` \
           60  `# 60s interval` \
@@ -144,8 +148,8 @@ get_credentials() {
     set -x
 }
 
-get_cac_token() {
-    log "--> Retrieving connector token before CAC install..."
+get_connector_token() {
+    log "--> Retrieving connector token before AWC install..."
 
     local args=""
 
@@ -160,17 +164,17 @@ get_cac_token() {
     dos2unix $PROVISIONING_DIR/$CAS_MGR_SCRIPT
     dos2unix $PROVISIONING_DIR/$CAS_MGR_DEPLOYMENT_SA_FILE
 
-    # Set CAC_TOKEN variable using the script's output
+    # Set AWC_TOKEN variable using the script's output
     if [ "$CAS_MGR_INSECURE" ]
     then
         args="--insecure"
     fi
 
-    PYTHONWARNINGS="ignore:Unverified HTTPS request" $PROVISIONING_DIR/$CAS_MGR_SCRIPT $PROVISIONING_DIR/$CAS_MGR_DEPLOYMENT_SA_FILE --url $CAS_MGR_URL --out $CAC_TOKEN_FILE $args
+    PYTHONWARNINGS="ignore:Unverified HTTPS request" $PROVISIONING_DIR/$CAS_MGR_SCRIPT $PROVISIONING_DIR/$CAS_MGR_DEPLOYMENT_SA_FILE --url $CAS_MGR_URL --out $AWC_TOKEN_FILE $args
     set +x
-    CAC_TOKEN=`cat $CAC_TOKEN_FILE`
+    AWC_TOKEN=`cat $AWC_TOKEN_FILE`
     set -x
-    rm $CAC_TOKEN_FILE
+    rm $AWC_TOKEN_FILE
 
     # Check and exit provisioning script if retrieving connector token failed
     if [ $? -ne 0 ]; then
@@ -186,48 +190,59 @@ check_required_vars() {
         missing_vars="true"
     fi
 
-    if [[ -z "$CAC_TOKEN" ]]; then
-        log "--> ERROR: Missing Cloud Access Connector Token."
+    if [[ -z "$AWC_TOKEN" ]]; then
+        log "--> ERROR: Missing Anyware Connector Token."
         missing_vars="true"
     fi
     set -x
 
-    if [[ "$missing_vars" = "true" ]]; then
+    if [[ "$missing_vars" == "true" ]]; then
         log "--> Exiting..."
         exit 1
     fi
 }
 
+configure_firewall(){
+    systemctl enable firewalld
+    systemctl start firewalld
+
+    firewall-cmd --permanent --add-port=6443/tcp # virtual network flannel
+    firewall-cmd --permanent --add-port=4172/tcp # PCoIP SG port
+    firewall-cmd --permanent --add-port=4172/udp # PCoIP SG port
+    firewall-cmd --permanent --zone=trusted --add-source=10.42.0.0/16 # This subnet is for the pods
+    firewall-cmd --permanent --zone=trusted --add-source=10.43.0.0/16 # This subnet is for the services
+    firewall-cmd --reload
+}
+
 check_connector_installed() {
-    if [[ -f "$CAC_BIN_PATH" ]]; then
+    if [[ -f "$AWC_BIN_PATH" ]]; then
         log "--> Connector already installed. Skipping provisioning script..."
         exit 0
     fi
 }
 
-config_network() {
-    if [[ ! -f $PCOIP_NETWORK_CONF_FILE ]]; then
-        log "--> Configuring network..."
-        # Note the indented HEREDOC lines must be preceded by tabs, not spaces
-        cat <<- EOF > $PCOIP_NETWORK_CONF_FILE
-			# System Control network settings for CAC
-			net.core.rmem_max=160000000
-			net.core.rmem_default=160000000
-			net.core.wmem_max=160000000
-			net.core.wmem_default=160000000
-			net.ipv4.udp_mem=120000 240000 600000
-			net.core.netdev_max_backlog=2000
-			EOF
-
-        sysctl -p $PCOIP_NETWORK_CONF_FILE
-    fi
+add_cas_mgr_repo() {
+    log "--> Adding CAS Manager repo..."
+    curl -1sLf $AWC_REPO_SETUP_SCRIPT_URL | distro=el codename=8 bash
+    dnf repolist --enabled teradici-cas-manager*
 }
 
-download_cac() {
-    log "--> Downloading CAC installer..."
-    cac_installer_url="$CAC_LOCATION_URL/$CAC_FILENAME"
-    curl -L $cac_installer_url -o $PROVISIONING_DIR/cloud-access-connector.tar.gz
-    tar xzvf $PROVISIONING_DIR/cloud-access-connector.tar.gz -C /
+config_selinux() {
+    log "--> Configuring SE Linux..."
+    dnf install -y selinux-policy-base container-selinux
+    dnf install -y https://github.com/k3s-io/k3s-selinux/releases/download/v1.1.stable.1/k3s-selinux-1.1-1.el8.noarch.rpm
+    dnf install -y cas-manager-selinux
+}
+
+install_awc() {
+    log "--> Installing Anyware Connector..."
+    dnf install -y cas-connector 2>&1 | tee -a $AWC_INSTALL_LOG
+
+    if [ $? -ne 0 ]
+    then
+        log "--> ERROR: Failed to install Anyware Connector..."
+        exit 1
+    fi
 }
 
 wait_for_dc() {
@@ -236,17 +251,11 @@ wait_for_dc() {
     # Note: using the domain controller IP instead of the domain name for
     #       the host is more resilient.
 
-    log "--> Updating apt-get package list..."
+    log "--> Installing utility packages..."
     retry 5 `# 5 retries` \
           5 `# 5s interval` \
-          "apt-get -qq update" \
-          "--> ERROR: Failed to update apt-get package list."
-
-    log "--> Installing ldap_utils..."
-    retry 5 `# 5 retries` \
-          5 `# 5s interval` \
-          "apt-get -qq install ldap-utils" \
-          "--> ERROR: Failed to install ldap-utils."
+          "dnf -y install bind-utils nc openldap-clients" \
+          "--> ERROR: Failed to install utility packages."
 
     set +x
     log "--> Ensure AD account is available..."
@@ -261,57 +270,68 @@ wait_for_dc() {
     set -x
     # Check that the domain name can be resolved and that the LDAP port is accepting
     # connections. This could have been all done with the ldapwhoami command, but
-    # due to a number of occasional cac-installation issues, such as "domain
+    # due to a number of occasional awc-installation issues, such as "domain
     # controller unreachable" or "DNS error occurred" errors, check these explicitly
     # for logging and debug purposes.
     log "--> Ensure domain $DOMAIN_NAME can be resolved..."
     retry 120 `# 120 retries` \
           10  `# 10s interval` \
           "host $DOMAIN_NAME" \
-          "--> ERROR: Failed to resolve $DOMAIN_NAME. Continuing..."
+          "--> ERROR: Failed to resolve $DOMAIN_NAME."
 
     log "--> Ensure domain $DOMAIN_NAME port 636 is reacheable..."
     retry 120 `# 120 retries` \
           10  `# 10s interval` \
-          "netcat -vz $DOMAIN_NAME 636" \
-          "--> ERROR: Failed to contact $DOMAIN_NAME:636. Continuing..."
+          "nc -vz $DOMAIN_NAME 636" \
+          "--> ERROR: Failed to contact $DOMAIN_NAME:636."
 }
 
-install_cac() {
-    log "--> Installing Cloud Access Connector..."
+download_ldaps_cert() {
+    log "--> Downloading LDAPS Cert..."
+    retry 120 `# 120 retries` \
+          10  `# 10s interval` \
+          "gsutil cp gs://$BUCKET_NAME/$LDAPS_CERT_FILENAME $PROVISIONING_DIR" \
+          "--> ERROR: Falied to download Domain Controller LDAPS certificate from GCS bucket."
+}
+
+configure_awc() {
+    log "--> Configuring Anyware Connector..."
     local args=""
 
-    log "--> Running command: $CAC_BIN_PATH install"
-    log "--> CAC install options:"
-    log "  -t <cac_token>"
+    log "--> Running command: $AWC_BIN_PATH install"
+    log "--> AWC install options:"
+    log "  --token <awc_token>"
+    log "  --computers-dn $COMPUTERS_DN"
+    log "  --users-dn $USERS_DN"
     log "  --accept-policies"
     log "  --sa-user <ad_service_account_username>"
     log "  --sa-password <ad_service_account_password>"
     log "  --domain $DOMAIN_NAME"
+    log "  --ldaps-ca-cert $PROVISIONING_DIR/$LDAPS_CERT_FILENAME"
     log "  --retrieve-agent-state true"
+    log "  --show-agent-state true"
     log "  --sync-interval 5"
     log "  --casm-url $CAS_MGR_URL"
-    log "  $CAC_EXTRA_INSTALL_FLAGS"
+    log "  $AWC_EXTRA_INSTALL_FLAGS"
 
     # Set pipefail option to return status of the connector install command
     set -o pipefail
 
-    if [ "$SSL_KEY" ]
+    if [ "$TLS_KEY" ]
     then
-        log "  --ssl-key <ssl_key>"
-        log "  --ssl-cert <ssl_cert>"
-        
+        log "  --tls-key <tls_key>"
+        log "  --tls-cert <tls_cert>"
         retry 3 `# 3 retries` \
               5 `# 5s interval` \
-              "gsutil cp gs://$BUCKET_NAME/$SSL_KEY $PROVISIONING_DIR" \
-              "--> ERROR: Failed to download ssl key from $BUCKET_NAME"
+              "gsutil cp gs://$BUCKET_NAME/$TLS_KEY $PROVISIONING_DIR" \
+              "--> ERROR: Failed to download TLS key from $BUCKET_NAME"
         retry 3 `# 3 retries` \
               5 `# 5s interval` \
-              "gsutil cp gs://$BUCKET_NAME/$SSL_CERT $PROVISIONING_DIR" \
-              "--> ERROR: Failed to download ssl cert from $BUCKET_NAME"
+              "gsutil cp gs://$BUCKET_NAME/$TLS_CERT $PROVISIONING_DIR" \
+              "--> ERROR: Failed to download TLS cert from $BUCKET_NAME"
 
-        args=$args"--ssl-key $PROVISIONING_DIR/$SSL_KEY "
-        args=$args"--ssl-cert $PROVISIONING_DIR/$SSL_CERT "
+        args=$args"--tls-key $PROVISIONING_DIR/$TLS_KEY "
+        args=$args"--tls-cert $PROVISIONING_DIR/$TLS_CERT "
     else
         log "  --self-signed"
         args=$args"--self-signed "
@@ -333,19 +353,23 @@ install_cac() {
 
     retry 10 `# 10 retries` \
           10 `# 10s interval` \
-          "$CAC_BIN_PATH install \
-            -t $CAC_TOKEN \
+          "$AWC_BIN_PATH configure \
+            --token $AWC_TOKEN \
             --accept-policies \
+            --computers-dn $COMPUTERS_DN \
+            --users-dn $USERS_DN \
             --sa-user $AD_SERVICE_ACCOUNT_USERNAME \
             --sa-password "$AD_SERVICE_ACCOUNT_PASSWORD" \
             --domain $DOMAIN_NAME \
+            --ldaps-ca-cert $PROVISIONING_DIR/$LDAPS_CERT_FILENAME \
             --retrieve-agent-state true \
+            --show-agent-state true \
             --sync-interval 5 \
             --casm-url $CAS_MGR_URL \
-            $CAC_EXTRA_INSTALL_FLAGS \
+            $AWC_EXTRA_INSTALL_FLAGS \
             $args \
-            2>&1 | tee -a $CAC_INSTALL_LOG" \
-          "--> ERROR: Failed to install Cloud Access Connector."
+            2>&1 | tee -a $AWC_INSTALL_LOG" \
+          "--> ERROR: Failed to install Anyware Connector."
 
     if [ $? -ne 0 ]
     then
@@ -353,9 +377,13 @@ install_cac() {
         exit 1
     fi
 
-    log "--> Successfully installed Cloud Access Connector."
-
+    log "--> Successfully configured Anyware Connector."
+    
     set -x
+}
+
+cleanup() {
+    rm $PROVISIONING_DIR/$LDAPS_CERT_FILENAME
 }
 
 if [[ ! -f "$LOG_FILE" ]]
@@ -365,13 +393,15 @@ then
     chmod +644 "$LOG_FILE"
 fi
 
-log "$(date)"
-
 # Print all executed commands to the terminal
 set -x
 
 # Redirect stdout and stderr to the log file
 exec &>>$LOG_FILE
+
+log "$(date) Running $0 as $(whoami)..."
+
+cd $PROVISIONING_DIR
 
 install_prereqs
 
@@ -382,20 +412,26 @@ fi
 
 get_credentials
 
-get_cac_token
-
-check_required_vars
+configure_firewall
 
 check_connector_installed
 
-config_network
+add_cas_mgr_repo
 
-download_cac
+config_selinux
+
+install_awc
 
 wait_for_dc
 
-install_cac
+download_ldaps_cert
 
-docker service ls
+get_connector_token
+
+check_required_vars
+
+configure_awc
+
+cleanup
 
 log "--> Provisioning script completed successfully."
