GCP: CAC handle insecure CAM
Updated CAC modules to handle using unverified HTTPS connection to talk
to CAM - this is needed for CAM Standalone as the initial version does
not have verified HTTPS.

Signed-off-by: Sherman Yin <syin@teradici.com>

diff --git a/modules/gcp/cac-regional/cac-provisioning.sh.tmpl b/modules/gcp/cac-regional/cac-provisioning.sh.tmpl
--- a/modules/gcp/cac-regional/cac-provisioning.sh.tmpl
+++ b/modules/gcp/cac-regional/cac-provisioning.sh.tmpl
@@ -8,6 +8,7 @@
 LOG_FILE="/var/log/teradici/provisioning.log"
 
 INSTALL_DIR="/root"
+CAC_TOKEN_FILE=$INSTALL_DIR/cac_token
 CAC_INSTALL_LOG="/var/log/teradici/cac-install.log"
 cd $INSTALL_DIR
 
@@ -50,17 +51,28 @@ install_prereqs() {
     apt-get -qq update
     apt install -y dos2unix python3
 
-    if [ $? -ne 0 ]; then
-        log "--> ERROR: Failed to install dos2unix, python3. Exiting provisioning script..."
+    if [ $? -ne 0 ]
+    then
+        log "--> ERROR: Failed to install prerequisites. Exiting provisioning script..."
         exit 1
     fi
 }
 
 get_credentials() {
+    # In some cases, the CAM Deployment Service Account key is generated by a
+    # new CAM Standalone VM that is being created in parallel as the CAC. Loop
+    # until the file is found in the storage bucket.
+    local timeout=7200
+    local interval=60
+
+    retry $timeout \
+          $interval \
+          "gsutil cp gs://${bucket_name}/${cam_deployment_sa_file} $INSTALL_DIR" \
+          "--> Downloading CAM Deployment Service Account key from the bucket ${bucket_name}..." \
+          "--> ERROR: Failed to download CAM deployment Service Account key from bucket ${bucket_name}."
+
     # Disable logging of secrets by wrapping the region with set +x and set -x
     set +x
-    log "--> Downloading CAM Deployment Service Account JSON file from the bucket..."
-    gsutil cp gs://${bucket_name}/${cam_deployment_sa_file} $INSTALL_DIR
 
     if [[ -z "${kms_cryptokey_id}" ]]; then
         log "--> Script is not using encryption for secrets."
@@ -92,6 +104,8 @@ get_credentials() {
 get_cac_token() {
     log "--> Retrieving connector token before CAC install..."
 
+    local args=""
+
     log "--> Downloading CAM python script from the bucket..."
     gsutil cp gs://${bucket_name}/${cam_script} $INSTALL_DIR
     chmod +x $INSTALL_DIR/${cam_script}
@@ -101,7 +115,14 @@ get_cac_token() {
     dos2unix $INSTALL_DIR/${cam_deployment_sa_file}
 
     # Set CAC_TOKEN variable using the script's output
-    CAC_TOKEN=`$INSTALL_DIR/${cam_script} $INSTALL_DIR/${cam_deployment_sa_file} --url ${cam_url}/api/v1`
+    if [ "${cam_insecure}" ]
+    then
+        args="--insecure"
+    fi
+
+    PYTHONWARNINGS="ignore:Unverified HTTPS request" $INSTALL_DIR/${cam_script} $INSTALL_DIR/${cam_deployment_sa_file} --url ${cam_url} --out $CAC_TOKEN_FILE $args
+    CAC_TOKEN=`cat $CAC_TOKEN_FILE`
+    rm $CAC_TOKEN_FILE
 
     # Check and exit provisioning script if retrieving connector token failed
     if [ $? -ne 0 ]; then
@@ -226,6 +247,7 @@ wait_for_dc() {
 install_cac() {
     log "--> Installing Cloud Access Connector..."
     local retries=10
+    local args=""
 
     log "--> Running command: $INSTALL_DIR/cloud-access-connector install"
     log "--> CAC install options:"
@@ -255,6 +277,12 @@ install_cac() {
     else
         log "  --insecure"
         args=$args"--insecure "
+    fi
+
+    if [ "${cam_insecure}" ]
+    then
+        log "  --cam-insecure"
+        args=$args"--cam-insecure "
     fi
 
     if [ "${external_pcoip_ip}" ]
