GCP: Split CAC into two modules
The original cac module is a higher level module that creates resources
shared between CACs from different regions.

A cac-regional module is created to contain CACs and region-specific
scripts.

With this method, the CACs are no longer a single list of instances
with different regions. This will help scaling the instances for a
region without affecting the resources from other regions.

This makes use of the new Terrafor 0.13 module features.

Signed-off-by: Sherman Yin <syin@teradici.com>

diff --git a/modules/gcp/cac-regional/cac-provisioning.sh.tmpl b/modules/gcp/cac-regional/cac-provisioning.sh.tmpl
--- a/modules/gcp/cac-regional/cac-provisioning.sh.tmpl
+++ b/modules/gcp/cac-regional/cac-provisioning.sh.tmpl
@@ -245,81 +245,57 @@ install_cac() {
     # Set pipefail option to return status of the connector install command
     set -o pipefail
 
-    set +x
-    if [ -z "${ssl_key}" ]; then
-        log "--insecure"
-
-        while true
-        do
-            $INSTALL_DIR/cloud-access-connector install \
-                -t $CAC_TOKEN \
-                --accept-policies \
-                --insecure \
-                --sa-user ${ad_service_account_username} \
-                --sa-password "$AD_SERVICE_ACCOUNT_PASSWORD" \
-                --domain ${domain_name} \
-                --domain-group "${domain_group}" \
-                --reg-code $PCOIP_REGISTRATION_CODE \
-                --retrieve-agent-state true \
-                --sync-interval 5 \
-                2>&1 | tee -a $CAC_INSTALL_LOG
-
-            local rc=$?
-            if [ $rc -eq 0 ]
-            then
-                log "--> Successfully installed Cloud Access Connector."
-                break
-            fi
-
-            if [ $retries -eq 0 ]
-            then
-                log "--> ERROR: Failed to install Cloud Access Connector. No retries remaining."
-                exit 1
-            fi
-
-            log "--> ERROR: Failed to install Cloud Access Connector. $retries retries remaining..."
-            retries=$((retries-1))
-            sleep 60
-        done
-    else
+    if [ "${ssl_key}" ]
+    then
         log "--ssl-key <ssl_key> --ssl-cert <ssl_cert>"
         gsutil cp gs://${bucket_name}/${ssl_key} $INSTALL_DIR
         gsutil cp gs://${bucket_name}/${ssl_cert} $INSTALL_DIR
 
-        while true
-        do
-            $INSTALL_DIR/cloud-access-connector install \
-                -t $CAC_TOKEN \
-                --accept-policies \
-                --ssl-key $INSTALL_DIR/${ssl_key} \
-                --ssl-cert $INSTALL_DIR/${ssl_cert} \
-                --sa-user ${ad_service_account_username} \
-                --sa-password "$AD_SERVICE_ACCOUNT_PASSWORD" \
-                --domain ${domain_name} \
-                --domain-group "${domain_group}" \
-                --reg-code $PCOIP_REGISTRATION_CODE \
-                --retrieve-agent-state true \
-                --sync-interval 5 \
-                2>&1 | tee -a $CAC_INSTALL_LOG
-
-            local rc=$?
-            if [ $rc -eq 0 ]
-            then
-                log "--> Successfully installed Cloud Access Connector."
-                break
-            fi
-
-            if [ $retries -eq 0 ]
-            then
-                log "--> ERROR: Failed to install Cloud Access Connector. No retries remaining."
-                exit 1
-            fi
-
-            log "--> ERROR: Failed to install Cloud Access Connector. $retries retries remaining..."
-            retries=$((retries-1))
-            sleep 60
-        done
+        args=$args"--ssl-key $INSTALL_DIR/${ssl_key} "
+        args=$args"--ssl-cert $INSTALL_DIR/${ssl_cert} "
+    else
+        log "--insecure"
+        args=$args"--insecure "
     fi
+
+    if [ "${external_pcoip_ip}" ]
+    then
+        args=$args"--external-pcoip-ip ${external_pcoip_ip} "
+    fi
+
+    set +x
+    while true
+    do
+        $INSTALL_DIR/cloud-access-connector install \
+            -t $CAC_TOKEN \
+            --accept-policies \
+            --sa-user ${ad_service_account_username} \
+            --sa-password "$AD_SERVICE_ACCOUNT_PASSWORD" \
+            --domain ${domain_name} \
+            --domain-group "${domain_group}" \
+            --reg-code $PCOIP_REGISTRATION_CODE \
+            --retrieve-agent-state true \
+            --sync-interval 5 \
+            $args \
+            2>&1 | tee -a $CAC_INSTALL_LOG
+
+        local rc=$?
+        if [ $rc -eq 0 ]
+        then
+            log "--> Successfully installed Cloud Access Connector."
+            break
+        fi
+
+        if [ $retries -eq 0 ]
+        then
+            log "--> ERROR: Failed to install Cloud Access Connector. No retries remaining."
+            exit 1
+        fi
+
+        log "--> ERROR: Failed to install Cloud Access Connector. $retries retries remaining..."
+        retries=$((retries-1))
+        sleep 60
+    done
     set -x
 }
 
