AWS: Define global variables using rendered variables
Defined global variables and replaced rendered variables with new global variables

Signed-off-by: Qi Dang <qdang@teradici.com>

diff --git a/modules/aws/centos-std/centos-std-provisioning.sh.tmpl b/modules/aws/centos-std/centos-std-provisioning.sh.tmpl
--- a/modules/aws/centos-std/centos-std-provisioning.sh.tmpl
+++ b/modules/aws/centos-std/centos-std-provisioning.sh.tmpl
@@ -4,12 +4,20 @@
 #
 # This source code is licensed under the MIT license found in the
 # LICENSE file in the root directory of this source tree.
+AD_SERVICE_ACCOUNT_PASSWORD=${ad_service_account_password}
+AD_SERVICE_ACCOUNT_USERNAME=${ad_service_account_username}
+AWS_REGION=${aws_region}
+CUSTOMER_MASTER_KEY_ID=${customer_master_key_id}
+DOMAIN_CONTROLLER_IP=${domain_controller_ip}
+DOMAIN_NAME=${domain_name}
+PCOIP_REGISTRATION_CODE=${pcoip_registration_code}
+TERADICI_DOWNLOAD_TOKEN=${teradici_download_token}
 
 exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
 
 LOG_FILE="/var/log/teradici/provisioning.log"
 METADATA_IP="http://169.254.169.254"
-TERADICI_REPO_SETUP_SCRIPT_URL="https://dl.teradici.com/${teradici_download_token}/pcoip-agent/cfg/setup/bash.rpm.sh"
+TERADICI_REPO_SETUP_SCRIPT_URL="https://dl.teradici.com/$TERADICI_DOWNLOAD_TOKEN/pcoip-agent/cfg/setup/bash.rpm.sh"
 
 log() {
     local message="$1"
@@ -43,22 +51,19 @@ retry() {
 get_credentials() {
     # Disable logging of secrets by wrapping the region with set +x and set -x
     set +x
-    if [[ -z "${customer_master_key_id}" ]]; then
+    if [[ -z "$CUSTOMER_MASTER_KEY_ID" ]]; then
         log "--> Script is not using encryption for secrets."
 
-        PCOIP_REGISTRATION_CODE="${pcoip_registration_code}"
-        AD_SERVICE_ACCOUNT_PASSWORD="${ad_service_account_password}"
-
     else
-        log "--> Script is using encryption key: '${customer_master_key_id}'."
+        log "--> Script is using encryption key: '$CUSTOMER_MASTER_KEY_ID'."
 
-        if [[ "${pcoip_registration_code}" ]]; then
+        if [[ "$PCOIP_REGISTRATION_CODE" ]]; then
             log "--> Decrypting pcoip_registration_code..."
-            PCOIP_REGISTRATION_CODE=$(aws kms decrypt --region ${aws_region} --ciphertext-blob fileb://<(echo "${pcoip_registration_code}" | base64 -d) --output text --query Plaintext | base64 -d)
+            PCOIP_REGISTRATION_CODE=$(aws kms decrypt --region $AWS_REGION --ciphertext-blob fileb://<(echo "$PCOIP_REGISTRATION_CODE" | base64 -d) --output text --query Plaintext | base64 -d)
         fi
 
         log "--> Decrypting ad_service_account_password..."
-        AD_SERVICE_ACCOUNT_PASSWORD=$(aws kms decrypt --region ${aws_region} --ciphertext-blob fileb://<(echo "${ad_service_account_password}" | base64 -d) --output text --query Plaintext | base64 -d)
+        AD_SERVICE_ACCOUNT_PASSWORD=$(aws kms decrypt --region $AWS_REGION --ciphertext-blob fileb://<(echo "$AD_SERVICE_ACCOUNT_PASSWORD" | base64 -d) --output text --query Plaintext | base64 -d)
     fi
     set -x
 }
@@ -69,6 +74,7 @@ check_required_vars() {
         log "--> ERROR: Missing Active Directory Service Account Password."
         missing_vars="true"
     fi
+
     set -x
 
     if [[ "$missing_vars" = "true" ]]; then
@@ -84,7 +90,7 @@ update_hostname() {
     REGION=`curl $METADATA_IP/latest/dynamic/instance-identity/document/ -H "X-aws-ec2-metadata-token: $TOKEN" | jq -r .region`
     NEW_HOSTNAME=`aws ec2 describe-tags --region $REGION --filters "Name=resource-id,Values=$ID" "Name=key,Values=Name" --output json | jq -r .Tags[0].Value`
 
-    sudo hostnamectl set-hostname $NEW_HOSTNAME.${domain_name}
+    sudo hostnamectl set-hostname $NEW_HOSTNAME.$DOMAIN_NAME
 }
 
 exit_and_restart() {
@@ -94,58 +100,54 @@ exit_and_restart() {
 }
 
 install_pcoip_agent() {
-    if ! (rpm -q pcoip-agent-standard)
-    then
-
-        log "--> Getting Teradici PCoIP agent repo..."
-        curl --retry 3 --retry-delay 5 -u "token:${teradici_download_token}" -1sLf $TERADICI_REPO_SETUP_SCRIPT_URL | bash
-        if [ $? -ne 0 ]; then
-            log "--> ERROR: Failed to install PCoIP agent repo."
-            exit 1
-        fi
-        log "--> PCoIP agent repo installed successfully."
-
-        log "--> Installing USB dependencies..."
-        retry   3 \
-                5 \
-                "yum install -y usb-vhci" \
-                "--> Non-zero exit status." \
-                "--> Warning: Failed to install usb-vhci."
-
-        log "--> Installing PCoIP standard agent..."
-        retry   3 \
-                5 \
-                "yum -y install pcoip-agent-standard" \
-                "--> Non-zero exit status." \
-                "--> ERROR: Failed to download PCoIP agent."
-        if [ $? -eq 1 ]; then
-            exit 1
-        fi
-        log "--> PCoIP agent installed successfully."
-
-        set +x
-        if [[ "${pcoip_registration_code}" ]]; then
-            log "--> Registering PCoIP agent license..."
-            n=0
-            while true; do
-                /usr/sbin/pcoip-register-host --registration-code="$PCOIP_REGISTRATION_CODE" && break
-                n=$[$n+1]
-
-                if [ $n -ge 10 ]; then
-                    log "--> ERROR: Failed to register PCoIP agent after $n tries."
-                    exit 1
-                fi
-
-                log "--> ERROR: Failed to register PCoIP agent. Retrying in 10s..."
-                sleep 10
-            done
-            log "--> PCoIP agent registered successfully."
-
-        else
-            log "--> No PCoIP Registration Code provided. Skipping PCoIP agent registration..."
-        fi
-        set -x
+    log "--> Getting Teradici PCoIP agent repo..."
+    curl --retry 3 --retry-delay 5 -u "token:$TERADICI_DOWNLOAD_TOKEN" -1sLf $TERADICI_REPO_SETUP_SCRIPT_URL | bash
+    if [ $? -ne 0 ]; then
+        log "--> ERROR: Failed to install PCoIP agent repo."
+        exit 1
     fi
+    log "--> PCoIP agent repo installed successfully."
+
+    log "--> Installing USB dependencies..."
+    retry   3 \
+            5 \
+            "yum install -y usb-vhci" \
+            "--> Non-zero exit status." \
+            "--> Warning: Failed to install usb-vhci."
+
+    log "--> Installing PCoIP standard agent..."
+    retry   3 \
+            5 \
+            "yum -y install pcoip-agent-standard" \
+            "--> Non-zero exit status." \
+            "--> ERROR: Failed to download PCoIP agent."
+    if [ $? -eq 1 ]; then
+        exit 1
+    fi
+    log "--> PCoIP agent installed successfully."
+
+    set +x
+    if [[ "$PCOIP_REGISTRATION_CODE" ]]; then
+        log "--> Registering PCoIP agent license..."
+        n=0
+        while true; do
+            /usr/sbin/pcoip-register-host --registration-code="$PCOIP_REGISTRATION_CODE" && break
+            n=$[$n+1]
+
+            if [ $n -ge 10 ]; then
+                log "--> ERROR: Failed to register PCoIP agent after $n tries."
+                exit 1
+            fi
+
+            log "--> ERROR: Failed to register PCoIP agent. Retrying in 10s..."
+            sleep 10
+        done
+        log "--> PCoIP agent registered successfully."
+
+    else
+        log "--> No PCoIP Registration Code provided. Skipping PCoIP agent registration..."
+    fi
+    set -x
 }
 
 # Join domain
@@ -153,9 +155,9 @@ join_domain() {
     local dns_record_file="dns_record"
     if [[ ! -f "$dns_record_file" ]]
     then
-        log "--> DOMAIN NAME: ${domain_name}"
-        log "--> USERNAME: ${ad_service_account_username}"
-        log "--> DOMAIN CONTROLLER: ${domain_controller_ip}"
+        log "--> DOMAIN NAME: $DOMAIN_NAME"
+        log "--> USERNAME: $AD_SERVICE_ACCOUNT_USERNAME"
+        log "--> DOMAIN CONTROLLER: $DOMAIN_CONTROLLER_IP"
 
         # default hostname has the form ip-10-0-0-1.us-west-1.compute.internal,
         # get the first part of it
@@ -163,11 +165,11 @@ join_domain() {
 
         # Wait for AD service account to be set up
         yum -y install openldap-clients
-        log "--> Waiting for AD account ${ad_service_account_username}@${domain_name} to be available..."
+        log "--> Waiting for AD account $AD_SERVICE_ACCOUNT_USERNAME@$DOMAIN_NAME to be available..."
         set +x
-        until ldapwhoami -H ldap://${domain_controller_ip} -D ${ad_service_account_username}@${domain_name} -w "$AD_SERVICE_ACCOUNT_PASSWORD" -o nettimeout=1 > /dev/null 2>&1
+        until ldapwhoami -H ldap://$DOMAIN_CONTROLLER_IP -D $AD_SERVICE_ACCOUNT_USERNAME@$DOMAIN_NAME -w "$AD_SERVICE_ACCOUNT_PASSWORD" -o nettimeout=1 > /dev/null 2>&1
         do
-            log "--> ${ad_service_account_username}@${domain_name} not available yet, retrying in 10 seconds..."
+            log "--> $AD_SERVICE_ACCOUNT_USERNAME@$DOMAIN_NAME not available yet, retrying in 10 seconds..."
             sleep 10
         done
         set -x
@@ -176,45 +178,45 @@ join_domain() {
         log "--> Installing required packages to join domain..."
         yum -y install sssd realmd oddjob oddjob-mkhomedir adcli samba-common samba-common-tools krb5-workstation openldap-clients policycoreutils-python
 
-        log "--> Joining the domain '${domain_name}'..."
+        log "--> Joining the domain '$DOMAIN_NAME'..."
         local retries=10
 
         set +x
         while true
         do
-            echo "$AD_SERVICE_ACCOUNT_PASSWORD" | realm join --user="${ad_service_account_username}@${domain_name}" "${domain_name}" --verbose >&2
+            echo "$AD_SERVICE_ACCOUNT_PASSWORD" | realm join --user="$AD_SERVICE_ACCOUNT_USERNAME@$DOMAIN_NAME" "$DOMAIN_NAME" --verbose >&2
 
             local rc=$?
             if [[ $rc -eq 0 ]]
             then
-                log "--> Successfully joined domain '${domain_name}'."
+                log "--> Successfully joined domain '$DOMAIN_NAME'."
                 break
             fi
 
             if [ $retries -eq 0 ]
             then
-                log "--> ERROR: Failed to join domain '${domain_name}'."
+                log "--> ERROR: Failed to join domain '$DOMAIN_NAME'."
                 return 106
             fi
 
-            log "--> ERROR: Failed to join domain '${domain_name}'. $retries retries remaining..."
+            log "--> ERROR: Failed to join domain '$DOMAIN_NAME'. $retries retries remaining..."
             retries=$((retries-1))
             sleep 60
         done
         set -x
 
-        domainname "$VM_NAME.${domain_name}"
-        echo "%${domain_name}\\\\Domain\\ Admins ALL=(ALL) ALL" > /etc/sudoers.d/sudoers
+        domainname "$VM_NAME.$DOMAIN_NAME"
+        echo "%$DOMAIN_NAME\\\\Domain\\ Admins ALL=(ALL) ALL" > /etc/sudoers.d/sudoers
 
         log "--> Registering with DNS..."
-        DOMAIN_UPPER=$(echo "${domain_name}" | tr '[:lower:]' '[:upper:]')
+        DOMAIN_UPPER=$(echo "$DOMAIN_NAME" | tr '[:lower:]' '[:upper:]')
         IP_ADDRESS=$(hostname -I | grep -Eo '10.([0-9]*\.){2}[0-9]*')
         set +x
-        echo "$AD_SERVICE_ACCOUNT_PASSWORD" | kinit "${ad_service_account_username}"@"$DOMAIN_UPPER"
+        echo "$AD_SERVICE_ACCOUNT_PASSWORD" | kinit "$AD_SERVICE_ACCOUNT_USERNAME"@"$DOMAIN_UPPER"
         set -x
         touch "$dns_record_file"
-        echo "server ${domain_controller_ip}" > "$dns_record_file"
-        echo "update add $VM_NAME.${domain_name} 600 a $IP_ADDRESS" >> "$dns_record_file"
+        echo "server $DOMAIN_CONTROLLER_IP" > "$dns_record_file"
+        echo "update add $VM_NAME.$DOMAIN_NAME 600 a $IP_ADDRESS" >> "$dns_record_file"
         echo "send" >> "$dns_record_file"
         nsupdate -g "$dns_record_file" > /var/sky
 
@@ -288,7 +290,12 @@ systemctl set-default graphical.target
 
 join_domain
 
-install_pcoip_agent
+if ! (rpm -q pcoip-agent-standard)
+then
+    install_pcoip_agent
+else
+    log "--> pcoip-agent-standard is already installed."
+fi
 
 update_firewall
 
