Fix retry functions
There were multiple versions of retry function in our scripts. For
consistency, we built a retry function and applied it across all
the scripts.

Signed-off-by: Qi Dang <qidang@hp.com>

diff --git a/modules/aws/centos-std/centos-std-provisioning.sh.tmpl b/modules/aws/centos-std/centos-std-provisioning.sh.tmpl
--- a/modules/aws/centos-std/centos-std-provisioning.sh.tmpl
+++ b/modules/aws/centos-std/centos-std-provisioning.sh.tmpl
@@ -7,7 +7,9 @@
 AD_SERVICE_ACCOUNT_PASSWORD=${ad_service_account_password}
 AD_SERVICE_ACCOUNT_USERNAME=${ad_service_account_username}
 AWS_REGION=${aws_region}
+BUCKET_NAME=${bucket_name}
 CLOUDWATCH_ENABLE=${cloudwatch_enable}
+CLOUDWATCH_SETUP_SCRIPT=${cloudwatch_setup_script}
 CUSTOMER_MASTER_KEY_ID=${customer_master_key_id}
 DOMAIN_CONTROLLER_IP=${domain_controller_ip}
 DOMAIN_NAME=${domain_name}
@@ -30,25 +32,27 @@ log() {
 
 # Try command until zero exit status or exit(1) when non-zero status after max tries
 retry() {
-    local counter="$1"
-    local interval="$2"
-    local command="$3"
-    local log_message="$4"
-    local err_message="$5"
-    local count=0
+    local retry="$1"         # number of retries
+    local retry_delay="$2"   # delay between each retry, in seconds
+    local shell_command="$3" # the shell command to run
+    local err_message="$4"   # the message to show when the shell command was not successful
 
-    while [ true ]
+    local retry_num=0
+    until eval $shell_command
     do
-        ((count=count+1))
-        eval $command && break
-        if [ $count -gt $counter ]
+        local rc=$?
+        local retry_remain=$((retry-retry_num))
+
+        if [ $retry_remain -eq 0 ]
         then
-            log "$err_message"
-            return 1
-        else
-            log "$log_message Retrying in $interval seconds"
-            sleep $interval
+            log $error_message
+            return $rc
         fi
+
+        log "$err_message Retrying in $retry_delay seconds... ($retry_remain retries remaining...)"
+
+        retry_num=$((retry_num+1))
+        sleep $retry_delay
     done
 }
 
@@ -57,13 +61,14 @@ setup_cloudwatch(){
     then
         log "--> Setting up AWS CloudWatch Logs..."
 
-        retry 3 5 "aws s3 cp s3://${bucket_name}/${cloudwatch_setup_script} ." \
-            "--> " \
-            "--> ERROR: Failed to download CloudWatch setup script."
-        chmod +x ${cloudwatch_setup_script}
-        dos2unix ${cloudwatch_setup_script}
+        retry 3 `# 3 retries` \
+              5 `# 5s interval` \
+              "aws s3 cp s3://$BUCKET_NAME/$CLOUDWATCH_SETUP_SCRIPT ." \
+              "--> ERROR: Failed to download CloudWatch setup script from s3://$BUCKET_NAME/$CLOUDWATCH_SETUP_SCRIPT."
+        chmod +x $CLOUDWATCH_SETUP_SCRIPT
+        dos2unix $CLOUDWATCH_SETUP_SCRIPT
 
-        . ${cloudwatch_setup_script} ${aws_region} \
+        . $CLOUDWATCH_SETUP_SCRIPT $AWS_REGION \
             $LOG_FILE                        "[%a %b %d %H:%M:%S %Z %Y]" \
             "/var/log/messages"              "%b %d %H:%M:%S" \
             "/var/log/pcoip-agent/agent.log" "%Y-%m-%dT%H:%M:%S.%fZ" \
@@ -133,17 +138,15 @@ install_pcoip_agent() {
     log "--> PCoIP agent repo installed successfully."
 
     log "--> Installing USB dependencies..."
-    retry   3 \
-            5 \
+    retry   3 `# 3 retries` \
+            5 `# 5s interval` \
             "yum install -y usb-vhci" \
-            "--> Non-zero exit status." \
             "--> Warning: Failed to install usb-vhci."
 
     log "--> Installing PCoIP standard agent..."
-    retry   3 \
-            5 \
+    retry   3 `# 3 retries` \
+            5 `# 5s interval` \
             "yum -y install pcoip-agent-standard" \
-            "--> Non-zero exit status." \
             "--> ERROR: Failed to download PCoIP agent."
     if [ $? -eq 1 ]; then
         exit 1
@@ -178,10 +181,9 @@ install_idle_shutdown() {
     log "--> Installing idle shutdown..."
     mkdir /tmp/idleShutdown
 
-    retry 3 \
-          5 \
-          "curl 'https://raw.githubusercontent.com/teradici/deploy/master/remote-workstations/new-agent-vm/Install-Idle-Shutdown.sh' --output /tmp/idleShutdown/Install-Idle-Shutdown-raw.sh" \
-          "-->" \
+    retry 3 `# 3 retries` \
+          5 `# 5s interval` \
+          "curl https://raw.githubusercontent.com/teradici/deploy/master/remote-workstations/new-agent-vm/Install-Idle-Shutdown.sh --output /tmp/idleShutdown/Install-Idle-Shutdown-raw.sh" \
           "--> ERROR: Failed to download Install-Idle-Shutdown.sh."
 
     awk '{ sub("\r$", ""); print }' /tmp/idleShutdown/Install-Idle-Shutdown-raw.sh > /tmp/idleShutdown/Install-Idle-Shutdown.sh && chmod +x /tmp/idleShutdown/Install-Idle-Shutdown.sh
@@ -192,11 +194,13 @@ install_idle_shutdown() {
         INSTALL_OPTS="$INSTALL_OPTS --disabled"
     fi
 
-    retry 3 5 "/tmp/idleShutdown/Install-Idle-Shutdown.sh $INSTALL_OPTS"
+    retry 3 `# 3 retries` \
+          5 `# 5s interval` \
+          "/tmp/idleShutdown/Install-Idle-Shutdown.sh $INSTALL_OPTS" \
+          "--> ERROR: Failed to install idle shutdown."
 
-    exitCode=$?
-    if [[ $exitCode -ne 0 ]]; then
-        log "--> ERROR: Failed to install idle shutdown."
+    if [[ $? -ne 0 ]]; then
+        log "--> Exiting provisioning script due to an error."
         exit 1
     fi
 
@@ -243,8 +247,7 @@ join_domain() {
         do
             echo "$AD_SERVICE_ACCOUNT_PASSWORD" | realm join --user="$AD_SERVICE_ACCOUNT_USERNAME@$DOMAIN_NAME" "$DOMAIN_NAME" --verbose >&2
 
-            local rc=$?
-            if [[ $rc -eq 0 ]]
+            if [[ $? -eq 0 ]]
             then
                 log "--> Successfully joined domain '$DOMAIN_NAME'."
                 break
diff --git a/modules/aws/ha-lls/lls-provisioning.sh.tmpl b/modules/aws/ha-lls/lls-provisioning.sh.tmpl
--- a/modules/aws/ha-lls/lls-provisioning.sh.tmpl
+++ b/modules/aws/ha-lls/lls-provisioning.sh.tmpl
@@ -18,27 +18,27 @@ log() {
 }
 
 retry() {
-    local timeout="$1"
-    local interval="$2"
-    local command="$3"
-    local log_message="$4"
-    local err_message="$5"
+    local retry="$1"         # number of retries
+    local retry_delay="$2"   # delay between each retry, in seconds
+    local shell_command="$3" # the shell command to run
+    local err_message="$4"   # the message to show when the shell command was not successful
 
-    while true
+    local retry_num=0
+    until eval $shell_command
     do
-        log "$log_message"
-        eval $command && break
+        local rc=$?
+        local retry_remain=$((retry-retry_num))
 
-        if [ $timeout -le 0 ]
+        if [ $retry_remain -eq 0 ]
         then
-            log "$err_message"
-            exit 1
+            log $error_message
+            return $rc
         fi
 
-        log "Retrying in $interval seconds... (Timeout in $timeout seconds)"
+        log "$err_message Retrying in $retry_delay seconds... ($retry_remain retries remaining...)"
 
-        timeout=$((timeout-interval))
-        sleep $interval
+        retry_num=$((retry_num+1))
+        sleep $retry_delay
     done
 }
 
@@ -47,7 +47,10 @@ setup_cloudwatch(){
     then
         log "--> Setting up AWS CloudWatch Logs..."
 
-        aws s3 cp s3://${bucket_name}/${cloudwatch_setup_script} .
+        retry 3 `# 3 retries` \
+              5 `# 5s interval` \
+              "aws s3 cp s3://${bucket_name}/${cloudwatch_setup_script} ." \
+              "--> ERROR: Failed to download CloudWatch setup script from s3://${bucket_name}/${cloudwatch_setup_script}."
         chmod +x ${cloudwatch_setup_script}
         dos2unix ${cloudwatch_setup_script}
 
@@ -114,10 +117,10 @@ send_msg_to() {
     local peer="$1"
     local msg="$2"
 
-    retry 600 10 \
-        "echo $msg | nc --send-only $peer $NCAT_PORT" \
-        "Sending message to $peer..." \
-        "ERROR: Failed to send message to $peer."
+    retry 60 `# 60 retries` \
+          10 `# 10s interval` \
+          "echo $msg | nc --send-only $peer $NCAT_PORT" \
+          "ERROR: Failed to send message to $peer."
 }
 
 # Wait for a message using ncat
diff --git a/modules/aws/lls/lls-provisioning.sh.tmpl b/modules/aws/lls/lls-provisioning.sh.tmpl
--- a/modules/aws/lls/lls-provisioning.sh.tmpl
+++ b/modules/aws/lls/lls-provisioning.sh.tmpl
@@ -18,26 +18,27 @@ log() {
 }
 
 retry() {
-    local timeout="$1"
-    local interval="$2"
-    local command="$3"
-    local log_message="$4"
-    local err_message="$5"
+    local retry="$1"         # number of retries
+    local retry_delay="$2"   # delay between each retry, in seconds
+    local shell_command="$3" # the shell command to run
+    local err_message="$4"   # the message to show when the shell command was not successful
 
-    log "$log_message"
-
-    while [ true ]
+    local retry_num=0
+    until eval $shell_command
     do
-        ((count=count+1))
-        eval $command && break
-        if [ $count -gt $counter ]
+        local rc=$?
+        local retry_remain=$((retry-retry_num))
+
+        if [ $retry_remain -eq 0 ]
         then
-            log "$err_message"
-            return 1
-        else
-            log "$log_message Retrying in $interval seconds"
-            sleep $interval
+            log $error_message
+            return $rc
         fi
+
+        log "$err_message Retrying in $retry_delay seconds... ($retry_remain retries remaining...)"
+
+        retry_num=$((retry_num+1))
+        sleep $retry_delay
     done
 }
 
@@ -46,7 +47,10 @@ setup_cloudwatch(){
     then
         log "--> Setting up AWS CloudWatch Logs..."
 
-        aws s3 cp s3://${bucket_name}/${cloudwatch_setup_script} .
+        retry 3 `# 3 retries` \
+              5 `# 5s interval` \
+              "aws s3 cp s3://${bucket_name}/${cloudwatch_setup_script} ." \
+              "--> ERROR: Failed to download CloudWatch setup script from s3://${bucket_name}/${cloudwatch_setup_script}."
         chmod +x ${cloudwatch_setup_script}
         dos2unix ${cloudwatch_setup_script}
 
diff --git a/modules/gcp/cac-igm/cac-provisioning.sh.tmpl b/modules/gcp/cac-igm/cac-provisioning.sh.tmpl
--- a/modules/gcp/cac-igm/cac-provisioning.sh.tmpl
+++ b/modules/gcp/cac-igm/cac-provisioning.sh.tmpl
@@ -28,24 +28,27 @@ log() {
 }
 
 retry() {
-    local timeout="$1"
-    local interval="$2"
-    local command="$3"
-    local log_message="$4"
-    local err_message="$5"
+    local retry="$1"         # number of retries
+    local retry_delay="$2"   # delay between each retry, in seconds
+    local shell_command="$3" # the shell command to run
+    local err_message="$4"   # the message to show when the shell command was not successful
 
-    until $command
+    local retry_num=0
+    until eval $shell_command
     do
-        if [ $timeout -le 0 ]
+        local rc=$?
+        local retry_remain=$((retry-retry_num))
+
+        if [ $retry_remain -eq 0 ]
         then
-            log $err_message
-            break
+            log $error_message
+            return $rc
         fi
 
-        log "$log_message Retrying in $interval seconds... (Timeout in $timeout seconds)"
+        log "$err_message Retrying in $retry_delay seconds... ($retry_remain retries remaining...)"
 
-        timeout=$((timeout-interval))
-        sleep $interval
+        retry_num=$((retry_num+1))
+        sleep $retry_delay
     done
 }
 
@@ -62,24 +65,19 @@ install_prereqs() {
 }
 
 setup_ops() {
-    local timeout=25
-    local interval=5
-
     if [[ -f "/etc/google-cloud-ops-agent/config.yaml" ]]
     then
         log "--> Ops Agent configuration file already exists, skipping custom Ops Agent configuration to avoid overwriting existing settings"
     else
         log "--> Setting up GCP OPs Agent..."
 
-        retry $timeout \
-              $interval \
+        retry 25 `# 25 retries` \
+              5  `# 5s interval` \
               "gsutil cp gs://${bucket_name}/${ops_setup_script} ." \
-              "--> Downloading Logging Agent from the bucket ${bucket_name}..." \
-              "--> ERROR: Failed to download Logging Agent from bucket ${bucket_name}."
+              "--> ERROR: Failed to download Logging Agent from gs://${bucket_name}/${ops_setup_script}."
 
         if [ $? -ne 0 ]; then
             log "--> ERROR: Failed to install GCP OPs Agent."
-            exit 1
         fi 
 
         chmod +x ${ops_setup_script}
@@ -96,13 +94,10 @@ get_credentials() {
     # In some cases, the CAS Manager Deployment Service Account key is
     # generated by a new CAS Manager VM that is being created in parallel as the
     # CAC. Loop until the file is found in the storage bucket.
-    local timeout=7200
-    local interval=60
 
-    retry $timeout \
-          $interval \
+    retry 120 `# 120 retries` \
+          60  `# 60s interval` \
           "gsutil cp gs://${bucket_name}/${cas_mgr_deployment_sa_file} $PROVISIONING_DIR" \
-          "--> Downloading CAS Manager Deployment Service Account key from the bucket ${bucket_name}..." \
           "--> ERROR: Failed to download CAS Manager Deployment Service Account key from bucket ${bucket_name}."
 
     # Disable logging of secrets by wrapping the region with set +x and set -x
@@ -137,7 +132,10 @@ get_cac_token() {
     local args=""
 
     log "--> Downloading CAS Manager python script from the bucket..."
-    gsutil cp gs://${bucket_name}/${cas_mgr_script} $PROVISIONING_DIR
+    retry 3 `# 3 retries` \
+          5 `# 5s interval` \
+          "gsutil cp gs://${bucket_name}/${cas_mgr_script} $PROVISIONING_DIR" \
+          "--> ERROR: Failed to download CAS Manager python script from gs://${bucket_name}/${cas_mgr_script}"
     chmod +x $PROVISIONING_DIR/${cas_mgr_script}
 
     # Ensure line endings are in Unix format
@@ -151,7 +149,9 @@ get_cac_token() {
     fi
 
     PYTHONWARNINGS="ignore:Unverified HTTPS request" $PROVISIONING_DIR/${cas_mgr_script} $PROVISIONING_DIR/${cas_mgr_deployment_sa_file} --url ${cas_mgr_url} --out $CAC_TOKEN_FILE $args
+    set +x
     CAC_TOKEN=`cat $CAC_TOKEN_FILE`
+    set -x
     rm $CAC_TOKEN_FILE
 
     # Check and exit provisioning script if retrieving connector token failed
@@ -167,12 +167,12 @@ check_required_vars() {
         log "--> ERROR: Missing Active Directory Service Account Password."
         missing_vars="true"
     fi
-    set -x
 
     if [[ -z "$CAC_TOKEN" ]]; then
         log "--> ERROR: Missing Cloud Access Connector Token."
         missing_vars="true"
     fi
+    set -x
 
     if [[ "$missing_vars" = "true" ]]; then
         log "--> Exiting..."
@@ -213,42 +213,33 @@ download_cac() {
 }
 
 wait_for_dc() {
-    local timeout=25
-    local interval=5
-
     # Wait for service account to be added. Do this last because it takes
     # a while for new AD user to be added in a new Domain Controller.
     # Note: using the domain controller IP instead of the domain name for
     #       the host is more resilient.
 
     log "--> Updating apt-get package list..."
-    retry $timeout \
-          $interval \
+    retry 5 `# 5 retries` \
+          5 `# 5s interval` \
           "apt-get -qq update" \
-          "--> Updating apt-get package list..." \
           "--> ERROR: Failed to update apt-get package list."
 
     log "--> Installing ldap_utils..."
-    retry $timeout \
-          $interval \
+    retry 5 `# 5 retries` \
+          5 `# 5s interval` \
           "apt-get -qq install ldap-utils" \
-          "--> Installing ldap_utils..." \
           "--> ERROR: Failed to install ldap-utils."
-
-    timeout=1200
-    interval=10
 
     set +x
     log "--> Ensure AD account is available..."
-    retry $timeout \
-          $interval \
+    retry 120 `# 120 retries` \
+          10  `# 10s interval` \
           "ldapwhoami \
             -H ldap://${domain_controller_ip} \
             -D ${ad_service_account_username}@${domain_name} \
             -w $AD_SERVICE_ACCOUNT_PASSWORD \
             -o nettimeout=1" \
-          "--> Waiting for AD account ${ad_service_account_username}@${domain_name} to become available." \
-          "--> ERROR: Timed out waiting for AD account ${ad_service_account_username}@${domain_name} to become available. Continuing..."
+          "--> ERROR: AD account ${ad_service_account_username}@${domain_name} is not available."
     set -x
     # Check that the domain name can be resolved and that the LDAP port is accepting
     # connections. This could have been all done with the ldapwhoami command, but
@@ -256,23 +247,20 @@ wait_for_dc() {
     # controller unreachable" or "DNS error occurred" errors, check these explicitly
     # for logging and debug purposes.
     log "--> Ensure domain ${domain_name} can be resolved..."
-    retry $timeout \
-          $interval \
+    retry 120 `# 120 retries` \
+          10  `# 10s interval` \
           "host ${domain_name}" \
-          "--> Trying to resolve ${domain_name}." \
-          "--> ERROR: Timed out trying to resolve ${domain_name}. Continuing..."
+          "--> ERROR: Failed to resolve ${domain_name}. Continuing..."
 
     log "--> Ensure domain ${domain_name} port 636 is reacheable..."
-    retry $timeout \
-          $interval \
+    retry 120 `# 120 retries` \
+          10  `# 10s interval` \
           "netcat -vz ${domain_name} 636" \
-          "--> Trying to contact ${domain_name}:636." \
-          "--> ERROR: Timed out trying to contact ${domain_name}:636. Continuing..."
+          "--> ERROR: Failed to contact ${domain_name}:636. Continuing..."
 }
 
 install_cac() {
     log "--> Installing Cloud Access Connector..."
-    local retries=10
     local args=""
 
     log "--> Running command: $CAC_BIN_PATH install"
@@ -294,8 +282,14 @@ install_cac() {
     then
         log "  --ssl-key <ssl_key>"
         log "  --ssl-cert <ssl_cert>"
-        gsutil cp gs://${bucket_name}/${ssl_key} $PROVISIONING_DIR
-        gsutil cp gs://${bucket_name}/${ssl_cert} $PROVISIONING_DIR
+        retry 3 `# 3 retries` \
+              5 `# 5s interval` \
+              "gsutil cp gs://${bucket_name}/${ssl_key} $PROVISIONING_DIR" \
+              "--> ERROR: Failed to download ssl key from ${bucket_name}"
+        retry 3 `# 3 retries` \
+              5 `# 5s interval` \
+              "gsutil cp gs://${bucket_name}/${ssl_cert} $PROVISIONING_DIR" \
+              "--> ERROR: Failed to download ssl cert from ${bucket_name}"
 
         args=$args"--ssl-key $PROVISIONING_DIR/${ssl_key} "
         args=$args"--ssl-cert $PROVISIONING_DIR/${ssl_cert} "
@@ -317,9 +311,10 @@ install_cac() {
     fi
 
     set +x
-    while true
-    do
-        $CAC_BIN_PATH install \
+
+    retry 10 `# 10 retries` \
+          10 `# 10s interval` \
+          "$CAC_BIN_PATH install \
             -t $CAC_TOKEN \
             --accept-policies \
             --sa-user ${ad_service_account_username} \
@@ -330,25 +325,17 @@ install_cac() {
             --casm-url ${cas_mgr_url} \
             ${cac_extra_install_flags} \
             $args \
-            2>&1 | tee -a $CAC_INSTALL_LOG
+            2>&1 | tee -a $CAC_INSTALL_LOG" \
+          "--> ERROR: Failed to install Cloud Access Connector."
 
-        local rc=$?
-        if [ $rc -eq 0 ]
-        then
-            log "--> Successfully installed Cloud Access Connector."
-            break
-        fi
+    if [ $? -ne 0 ]
+    then
+        log "--> Exiting provisioning script due to an error."
+        exit 1
+    fi
 
-        if [ $retries -eq 0 ]
-        then
-            log "--> ERROR: Failed to install Cloud Access Connector. No retries remaining."
-            exit 1
-        fi
-
-        log "--> ERROR: Failed to install Cloud Access Connector. $retries retries remaining..."
-        retries=$((retries-1))
-        sleep 60
-    done
+    log "--> Successfully installed Cloud Access Connector."
+    
     set -x
 }
 
diff --git a/modules/gcp/cas-mgr/cas-mgr-provisioning.sh.tmpl b/modules/gcp/cas-mgr/cas-mgr-provisioning.sh.tmpl
--- a/modules/gcp/cas-mgr/cas-mgr-provisioning.sh.tmpl
+++ b/modules/gcp/cas-mgr/cas-mgr-provisioning.sh.tmpl
@@ -24,48 +24,44 @@ log() {
 }
 
 retry() {
-    local timeout="$1"
-    local interval="$2"
-    local command="$3"
-    local log_message="$4"
-    local err_message="$5"
+    local retry="$1"         # number of retries
+    local retry_delay="$2"   # delay between each retry, in seconds
+    local shell_command="$3" # the shell command to run
+    local err_message="$4"   # the message to show when the shell command was not successful
 
-    log "$log_message"
-
-    until $command
+    local retry_num=0
+    until eval $shell_command
     do
-        if [ $timeout -le 0 ]
+        local rc=$?
+        local retry_remain=$((retry-retry_num))
+
+        if [ $retry_remain -eq 0 ]
         then
-            log $err_message
-            break
+            log $error_message
+            return $rc
         fi
 
-        log "$log_message Retrying in $interval seconds... (Timeout in $timeout seconds)"
+        log "$err_message Retrying in $retry_delay seconds... ($retry_remain retries remaining...)"
 
-        timeout=$((timeout-interval))
-        sleep $interval
+        retry_num=$((retry_num+1))
+        sleep $retry_delay
     done
 }
 
 setup_ops() {
-    local timeout=25
-    local interval=5
-
     if [[ -f "/etc/google-cloud-ops-agent/config.yaml" ]]
     then
         log "--> Ops Agent configuration file already exists, skipping custom Ops Agent configuration to avoid overwriting existing settings"
     else
         log "--> Setting up GCP OPs Agent..."
 
-        retry $timeout \
-              $interval \
+        retry 25 `# 25 retries` \
+              5  `# 5s interval` \
               "gsutil cp gs://${bucket_name}/${ops_setup_script} ." \
-              "--> Downloading Logging Agent from the bucket ${bucket_name}..." \
-              "--> ERROR: Failed to download Logging Agent from bucket ${bucket_name}."
+              "--> ERROR: Failed to download Logging Agent from gs://${bucket_name}/${ops_setup_script}."
 
         if [ $? -ne 0 ]; then
             log "--> ERROR: Failed to install GCP OPs Agent."
-            exit 1
         fi 
 
         chmod +x ${ops_setup_script}
@@ -101,10 +97,10 @@ install_prereqs() {
 get_credentials() {
     if [ "${gcp_sa_file}" ]
     then
-        retry 7200 10 \
-            "gsutil cp gs://${bucket_name}/${gcp_sa_file} $INSTALL_DIR" \
-            "--> Downloading GCP Service Account key from the bucket ${bucket_name}..." \
-            "--> ERROR: Failed to download GCP Service Account key from bucket ${bucket_name}."
+        retry 720 `# 720 retries` \
+              10  `# 10s interval` \
+              "gsutil cp gs://${bucket_name}/${gcp_sa_file} $INSTALL_DIR" \
+              "--> ERROR: Failed to download GCP Service Account key from bucket ${bucket_name}."
     fi
 
     # Disable logging of secrets by wrapping the region with set +x and set -x
@@ -206,10 +202,10 @@ cas_mgr_setup() {
 
     log "--> Running CAS Manager setup script..."
 
-    retry 7200 10 \
+    retry 720 `# 720 retries` \
+          10  `# 10s interval` \
           "gsutil cp gs://${bucket_name}/${cas_mgr_setup_script} $INSTALL_DIR" \
-          "--> Downloading CAS Manager setup script from bucket ${bucket_name}..." \
-          "--> ERROR: Failed to download CAS Manager setup script from bucket ${bucket_name}."
+          "--> ERROR: Failed to download CAS Manager setup script from gs://${bucket_name}/${cas_mgr_setup_script}."
 
     dos2unix $INSTALL_DIR/${cas_mgr_setup_script}
     chmod +x $INSTALL_DIR/${cas_mgr_setup_script}
@@ -266,11 +262,14 @@ upload_dsa_key() {
 
     log "--> Uploading Deployment Service Account Key to bucket ${bucket_name}..."
 
-    gsutil cp $INSTALL_DIR/${cas_mgr_deployment_sa_file} gs://${bucket_name}/
+    retry 5 `# 5 retries`\
+          5 `# 5s interval` \
+          "gsutil cp $INSTALL_DIR/${cas_mgr_deployment_sa_file} gs://${bucket_name}/"
+          "--> ERROR: Failed to upload Deployment Service Account Key to bucket ${bucket_name}"
 
     if [ $? -ne 0 ]
     then
-        log "--> ERROR: Failed to upload CAS Manager deployment service account key to bucket ${bucket_name}. Exiting provisioning script..."
+        log "--> Exiting provisioning script due to an error."
         exit 1
     fi
 }
diff --git a/modules/gcp/centos-gfx/centos-gfx-provisioning.sh.tmpl b/modules/gcp/centos-gfx/centos-gfx-provisioning.sh.tmpl
--- a/modules/gcp/centos-gfx/centos-gfx-provisioning.sh.tmpl
+++ b/modules/gcp/centos-gfx/centos-gfx-provisioning.sh.tmpl
@@ -33,24 +33,28 @@ log() {
 }
 
 retry() {
-    local retries=0
-    local max_retries=3
-    until [[ $retries -ge $max_retries ]]
-    do  
-    # Break if command succeeds, or log the retry if command fails.
-        $@ && break || {
+    local retry="$1"         # number of retries
+    local retry_delay="$2"   # delay between each retry, in seconds
+    local shell_command="$3" # the shell command to run
+    local err_message="$4"   # the message to show when the shell command was not successful
 
-            log "--> Failed to run command. $@"
-            log "--> Retries left... $(( $max_retries - $retries ))"
-            ((retries++))
-            sleep 10;
-        }
+    local retry_num=0
+    until eval $shell_command
+    do
+        local rc=$?
+        local retry_remain=$((retry-retry_num))
+
+        if [ $retry_remain -eq 0 ]
+        then
+            log $error_message
+            return $rc
+        fi
+
+        log "$err_message Retrying in $retry_delay seconds... ($retry_remain retries remaining...)"
+
+        retry_num=$((retry_num+1))
+        sleep $retry_delay
     done
-
-    if [[ $retries -eq $max_retries ]]
-    then
-        return 1
-    fi
 }
 
 setup_ops() {
@@ -60,11 +64,10 @@ setup_ops() {
     else
         log "--> Setting up GCP OPs Agent..."
 
-        retry "gsutil cp gs://$BUCKET_NAME/$OPS_SETUP_SCRIPT ."
-        if [ $? -ne 0 ]; then
-            log "--> ERROR: Failed to install GCP OPs agent."
-            exit 1
-        fi 
+        retry 25 `# 25 retries` \
+              5  `# 5s interval` \
+              "gsutil cp gs://$BUCKET_NAME/$OPS_SETUP_SCRIPT ." \
+              "--> ERROR: Failed to download Logging Agent from gs://$BUCKET_NAME/$OPS_SETUP_SCRIPT."
 
         chmod +x $OPS_SETUP_SCRIPT
 
@@ -130,15 +133,13 @@ exit_and_restart() {
 install_kernel_header() {
     log "--> Installing kernel headers and development packages..."
     yum install kernel-devel kernel-headers -y
-    exitCode=$?
-    if [[ $exitCode -ne 0 ]]; then
+    if [[ $? -ne 0 ]]; then
         log "--> ERROR: Failed to install kernel header."
         exit 1
     fi
 
     yum install gcc -y
-    exitCode=$?
-    if [[ $exitCode -ne 0 ]]; then
+    if [[ $? -ne 0 ]]; then
         log "--> ERROR: Failed to install gcc."
         exit 1
     fi
@@ -161,7 +162,10 @@ install_gpu_driver() {
         systemctl stop gdm
 
         log "--> Downloading GPU driver $nvidia_driver_filename to $gpu_installer..."
-        retry "curl -f -o $gpu_installer $NVIDIA_DRIVER_URL"
+        retry 3 `# 3retries` \
+              5 `#5s interval` \
+              "curl -f -o $gpu_installer $NVIDIA_DRIVER_URL" \
+              "--> ERROR: Failed to download GPU driver installer."
         chmod u+x "$gpu_installer"
         log "--> Running GPU driver installer..."
 
@@ -221,14 +225,20 @@ install_pcoip_agent() {
     log "--> PCoIP agent repo installed successfully."
 
     log "--> Installing USB dependencies..."
-    retry "yum install -y usb-vhci"
+    retry 3 `# 3 retries` \
+          5 `# 5s interval` \
+          "yum install -y usb-vhci" \
+          "--> Warning: Failed to install usb-vhci."
     if [ $? -ne 0 ]; then
         log "--> Warning: Failed to install usb-vhci."
     fi
     log "--> usb-vhci successfully installed."
 
     log "--> Installing PCoIP graphics agent..."
-    retry yum -y install pcoip-agent-graphics
+    retry 3 `# 3 retries` \
+          5 `# 5s interval` \
+          "yum -y install pcoip-agent-graphics" \
+          "--> ERROR: Failed to download PCoIP agent."
     if [ $? -ne 0 ]; then
         log "--> ERROR: Failed to install PCoIP agent."
         exit 1
@@ -258,7 +268,10 @@ install_idle_shutdown() {
     log "--> Installing idle shutdown..."
     mkdir /tmp/idleShutdown
 
-    retry curl "https://raw.githubusercontent.com/teradici/deploy/master/remote-workstations/new-agent-vm/Install-Idle-Shutdown.sh" --output /tmp/idleShutdown/Install-Idle-Shutdown-raw.sh
+    retry 3 `# 3 retries` \
+          5 `# 5s interval` \
+          "curl 'https://raw.githubusercontent.com/teradici/deploy/master/remote-workstations/new-agent-vm/Install-Idle-Shutdown.sh' --output /tmp/idleShutdown/Install-Idle-Shutdown-raw.sh" \
+          "--> ERROR: Failed to download Install-Idle-Shutdown.sh."
 
     awk '{ sub("\r$", ""); print }' /tmp/idleShutdown/Install-Idle-Shutdown-raw.sh > /tmp/idleShutdown/Install-Idle-Shutdown.sh && chmod +x /tmp/idleShutdown/Install-Idle-Shutdown.sh
 
@@ -268,11 +281,13 @@ install_idle_shutdown() {
         INSTALL_OPTS="$INSTALL_OPTS --disabled"
     fi
 
-    retry /tmp/idleShutdown/Install-Idle-Shutdown.sh $INSTALL_OPTS
+    retry 3 `# 3 retries` \
+          5 `# 5s interval` \
+          "/tmp/idleShutdown/Install-Idle-Shutdown.sh $INSTALL_OPTS" \
+          "--> ERROR: Failed to install idle shutdown."
 
-    exitCode=$?
-    if [[ $exitCode -ne 0 ]]; then
-        log "--> ERROR: Failed to install idle shutdown."
+    if [[ $? -ne 0 ]]; then
+        log "--> Exiting provisioning script due to an error."
         exit 1
     fi
 
@@ -316,8 +331,7 @@ join_domain() {
         do
             echo "$AD_SERVICE_ACCOUNT_PASSWORD" | realm join --user="$AD_SERVICE_ACCOUNT_USERNAME@$DOMAIN_NAME" "$DOMAIN_NAME" --verbose >&2
 
-            local rc=$?
-            if [[ $rc -eq 0 ]]
+            if [[ $? -eq 0 ]]
             then
                 log "--> Successfully joined domain '$DOMAIN_NAME'."
                 break
