Use CAM service account instead of CAC token (multi-region)
To support autoscaling of CAC's in the future, we will need to generate
new CAC tokens to be used during CAC installations. In order to generate
CAC tokens, we have used a python script which will make calls to the
CAM API using the user-provided CAM service account credentials.

Both plaintext and encrypted secrets is supported for this multi-region
deployment using CAM service account instead of CAC token.

Signed-off-by: Edwin Pau <epau@teradici.com>

diff --git a/modules/gcp/cac-igm/cac-startup.sh.tmpl b/modules/gcp/cac-igm/cac-startup.sh.tmpl
--- a/modules/gcp/cac-igm/cac-startup.sh.tmpl
+++ b/modules/gcp/cac-igm/cac-startup.sh.tmpl
@@ -18,45 +18,88 @@ log() {
     echo "[$(date)] $${message}" | tee -a "$INSTALL_LOG"
 }
 
+get_cac_token() {
+    echo '### Retrieve connector token before CAC install ###'
+    log "Retrieving connector token..."
+
+    # Download the CAM python script from the bucket and run it to create a cac token
+    gsutil cp gs://${bucket_name}/${cam_script} $INSTALL_DIR
+    chmod +x ${cam_script}
+
+    # Set CAC_TOKEN variable using the script's output
+    CAC_TOKEN=`./${cam_script} ${cam_credentials_file}`
+
+    # Check and exit startup script if retrieving connector token failed
+    if [ $? -ne 0 ]; then
+        log "Failed to retrieve connector token. Exiting startup script..."
+        exit 1
+    fi
+}
+
 get_credentials() {
+    # Download the CAM credentials JSON file from the bucket
+    gsutil cp gs://${bucket_name}/${cam_credentials_file} $INSTALL_DIR
+
+    # Download and install python, python3
+    apt-get -qq update
+    apt install -y python
+    apt install -y python3
+
     if [[ -z "${kms_cryptokey_id}" ]]; then
-        log "Not using encryption"
+        log "Not using encryption..."
 
         PCOIP_REGISTRATION_CODE=${pcoip_registration_code}
         AD_SERVICE_ACCOUNT_PASSWORD=${ad_service_account_password}
-        CAC_TOKEN=${cac_token}
 
     else
-        log "Using encryption key ${kms_cryptokey_id}"
-
-        apt-get -qq update
-        apt install -y python
+        log "Using encryption key ${kms_cryptokey_id}..."
 
         # Gets access token attribute of response json object
-        token=$(curl "$METADATA_AUTH_URI" -H "Metadata-Flavor: Google" | python -c "import sys, json; print json.load(sys.stdin)['access_token']")
+        token=$(curl "$METADATA_AUTH_URI" -H "Metadata-Flavor: Google" \
+                                          | python -c "import sys, json; print json.load(sys.stdin)['access_token']")
 
         # Gets data using access token and decodes it
         data=$(echo "{ \"ciphertext\": \"${pcoip_registration_code}\" }")
-        b64_data=$(curl -X POST -d "$data" "$DECRYPT_URI" -H "Authorization: Bearer $token" -H "Content-type: application/json" | python -c "import sys, json; print json.load(sys.stdin)['plaintext']")
+        b64_data=$(curl -X POST \
+                        -d "$data" "$DECRYPT_URI" \
+                        -H "Authorization: Bearer $token" \
+                        -H "Content-type: application/json" \
+                        | python -c "import sys, json; print json.load(sys.stdin)['plaintext']")
         PCOIP_REGISTRATION_CODE=$(echo "$b64_data" | base64 --decode)
 
         data=$(echo "{ \"ciphertext\": \"${ad_service_account_password}\" }")
-        b64_data=$(curl -X POST -d "$data" "$DECRYPT_URI" -H "Authorization: Bearer $token" -H "Content-type: application/json" | python -c "import sys, json; print json.load(sys.stdin)['plaintext']")
+        b64_data=$(curl -X POST \
+                        -d "$data" "$DECRYPT_URI" \
+                        -H "Authorization: Bearer $token" \
+                        -H "Content-type: application/json" \
+                        | python -c "import sys, json; print json.load(sys.stdin)['plaintext']")
         AD_SERVICE_ACCOUNT_PASSWORD=$(echo "$b64_data" | base64 --decode)
 
-        data=$(echo "{ \"ciphertext\": \"${cac_token}\" }")
-        b64_data=$(curl -X POST -d "$data" "$DECRYPT_URI" -H "Authorization: Bearer $token" -H "Content-type: application/json" | python -c "import sys, json; print json.load(sys.stdin)['plaintext']")
-        CAC_TOKEN=$(echo "$b64_data" | base64 --decode)
+        # Gets decrypted CAM service account credentials and outputs to plaintext json file
+        cam_cred_encrypted=$(cat ${cam_credentials_file})
+        data=$(echo "{ \"ciphertext\": \"$cam_cred_encrypted\" }")
+        b64_data=$(curl -X POST 
+                        -d "$data" "$DECRYPT_URI" \
+                        -H "Authorization: Bearer $token" \
+                        -H "Content-type: application/json" \
+                        | python -c "import sys, json; print json.load(sys.stdin)['plaintext']")
+        CAM_CREDENTIALS=$(echo "$b64_data" | base64 --decode)
+        echo $CAM_CREDENTIALS | tee ${cam_credentials_file}
     fi
+
+    get_cac_token
 
     # Exit if any of the required variables are missing
     if [[ -z "$PCOIP_REGISTRATION_CODE" || -z "$AD_SERVICE_ACCOUNT_PASSWORD" || -z "$CAC_TOKEN" ]]; then
+        log "One of the following required variables is missing: \
+             PCOIP_REGISTRATION_CODE, AD_SERVICE_ACCOUNT_PASSWORD, CAC_TOKEN \
+             Exiting startup script..."
         exit 1
     fi
 }
 
 if [[ -f "$INSTALL_DIR/cloud-access-connector" ]]; then
-    log "Connector already installed. Skipping startup script."
+    log "Connector already installed. Skipping startup script..."
     exit 0
 fi
 
@@ -81,7 +124,7 @@ if [ ! -f $PCOIP_NETWORK_CONF_FILE ]; then
 fi
 
 
-# download CAC installer
+# Download CAC installer
 curl -L ${cac_installer_url} -o $INSTALL_DIR/cloud-access-connector.tar.gz
 tar xzvf $INSTALL_DIR/cloud-access-connector.tar.gz
 
