Workstations to get startup scripts from bucket
Instead of logging into workstations to upload and execute startup
scripts, upload the scripts to a bucket and refer to those scripts from
the workstations.

This makes it possible for workstations to be created without a public
IP in the future, and secrets are no longer in the meta-data field of
the instances.

However, workstation provisioning process can no longer be seen from
terraform host.

Signed-off-by: Sherman Yin <syin@teradici.com>

diff --git a/modules/gcp/centos-gfx/centos-gfx-startup.sh.tmpl b/modules/gcp/centos-gfx/centos-gfx-startup.sh.tmpl
--- a/modules/gcp/centos-gfx/centos-gfx-startup.sh.tmpl
+++ b/modules/gcp/centos-gfx/centos-gfx-startup.sh.tmpl
@@ -5,12 +5,13 @@
 
 #!/bin/bash
 
+INST_LOG_FILE="/var/log/teradici/agent/install.log"
 NVIDIA_GRID_VERSION=7.1
 NVIDIA_DRIVER_VERSION=410.92
 
 log() {
     local message="$1"
-    echo "[$(date)] ${message}" | tee -a "$INST_LOG_FILE"
+    echo "[$(date)] $${message}" | tee -a "$INST_LOG_FILE"
 }
 
 exit_and_restart()
@@ -53,9 +54,9 @@ install_gpu_driver() {
     if [[ $(lspci -d '10de:*:0300' -s '.0' | wc -l) -gt 0 ]] && ! (modprobe --resolve-alias nvidia > /dev/null 2>&1)
     then
         log "--> Start to install gpu driver ..."
-        local gpu_installer="/tmp/NVIDIA-Linux-x86_64-${NVIDIA_DRIVER_VERSION}-grid.run"
+        local gpu_installer="/tmp/NVIDIA-Linux-x86_64-$${NVIDIA_DRIVER_VERSION}-grid.run"
         log "--> Downloading gpu driver ..."
-        wget --retry-connrefused --tries=3 --waitretry=5 -O "$gpu_installer" https://storage.googleapis.com/nvidia-drivers-us-public/GRID/GRID${NVIDIA_GRID_VERSION}/NVIDIA-Linux-x86_64-${NVIDIA_DRIVER_VERSION}-grid.run
+        wget --retry-connrefused --tries=3 --waitretry=5 -O "$gpu_installer" https://storage.googleapis.com/nvidia-drivers-us-public/GRID/GRID$${NVIDIA_GRID_VERSION}/NVIDIA-Linux-x86_64-$${NVIDIA_DRIVER_VERSION}-grid.run
         chmod u+x "$gpu_installer"
         log "--> Running gpu driver installer ..."
 
@@ -134,7 +135,7 @@ install_pcoip_agent() {
 
         # Register the pcoip agent
         log "--> Register pcoip agent license ..."
-        /usr/sbin/pcoip-register-host --registration-code="$REGISTRATION_CODE"
+        /usr/sbin/pcoip-register-host --registration-code="${pcoip_registration_code}"
         log "--> Pcoip agent is installed successfully"
     fi
 }
@@ -145,18 +146,18 @@ join_domain()
     local dns_record_file="dns_record"
     if [[ ! -f "$dns_record_file" ]]
     then
-        log "--> DOMAIN NAME: $DOMAIN_NAME"
-        log "--> USERNAME: $USERNAME"
-        log "--> DOMAIN CONTROLLER: $IP_ADDRESS"
+        log "--> DOMAIN NAME: ${domain_name}"
+        log "--> USERNAME: ${service_account_username}"
+        log "--> DOMAIN CONTROLLER: ${domain_controller_ip}"
 
         VM_NAME=$(hostname)
 
         # Wait for AD service account to be set up
         yum -y install openldap-clients
-        log "--> Wait for AD account $USERNAME@$DOMAIN_NAME to be available"
-        until ldapwhoami -H ldap://$IP_ADDRESS -D $USERNAME@$DOMAIN_NAME -w $PASSWORD -o nettimeout=1 > /dev/null 2>&1
+        log "--> Wait for AD account ${service_account_username}@${domain_name} to be available"
+        until ldapwhoami -H ldap://${domain_controller_ip} -D ${service_account_username}@${domain_name} -w ${service_account_password} -o nettimeout=1 > /dev/null 2>&1
         do
-            log "$USERNAME@$DOMAIN_NAME not available yet, retrying in 10 seconds..."
+            log "${service_account_username}@${domain_name} not available yet, retrying in 10 seconds..."
             sleep 10
         done
 
@@ -181,16 +182,16 @@ join_domain()
         log "--> Joining the domain"
         if [[ -n "$OU" ]]
         then
-            echo "$PASSWORD" | realm join --user="$USERNAME" --computer-ou="$OU" "$DOMAIN_NAME" >&2
+            echo "${service_account_password}" | realm join --user="${service_account_username}" --computer-ou="$OU" "${domain_name}" >&2
         else
-            echo "$PASSWORD" | realm join --user="$USERNAME" "$DOMAIN_NAME" >&2
+            echo "${service_account_password}" | realm join --user="${service_account_username}" "${domain_name}" >&2
         fi
         exitCode=$?
         if [[ $exitCode -eq 0 ]]
         then
-            log "--> Joined Domain '$DOMAIN_NAME' and OU '$OU'"
+            log "--> Joined Domain '${domain_name}' and OU '$OU'"
         else
-            log "--> Failed to join Domain '$DOMAIN_NAME' and OU '$OU'"
+            log "--> Failed to join Domain '${domain_name}' and OU '$OU'"
             return 106
         fi
 
@@ -198,15 +199,15 @@ join_domain()
         sed -i '$ a\dyndns_update = True\ndyndns_ttl = 3600\ndyndns_refresh_interval = 43200\ndyndns_update_ptr = True\nldap_user_principal = nosuchattribute' /etc/sssd/sssd.conf
         sed -c -i "s/\\(use_fully_qualified_names *= *\\).*/\\1False/" /etc/sssd/sssd.conf
         sed -c -i "s/\\(fallback_homedir *= *\\).*/\\1\\/home\\/%u/" /etc/sssd/sssd.conf
-        domainname "$VM_NAME.$DOMAIN_NAME"
-        echo "%$DOMAIN_NAME\\\\Domain\\ Admins ALL=(ALL) ALL" > /etc/sudoers.d/sudoers
+        domainname "$VM_NAME.${domain_name}"
+        echo "%${domain_name}\\\\Domain\\ Admins ALL=(ALL) ALL" > /etc/sudoers.d/sudoers
 
         log "--> Registering with DNS"
-        DOMAIN_UPPER=$(echo "$DOMAIN_NAME" | tr '[:lower:]' '[:upper:]')
+        DOMAIN_UPPER=$(echo "${domain_name}" | tr '[:lower:]' '[:upper:]')
         IP_ADDRESS=$(hostname -I | grep -Eo '10.([0-9]*\.){2}[0-9]*')
-        echo "$PASSWORD" | kinit "$USERNAME"@"$DOMAIN_UPPER"
+        echo "${service_account_password}" | kinit "${service_account_username}"@"$DOMAIN_UPPER"
         touch "$dns_record_file"
-        echo "update add $VM_NAME.$DOMAIN_NAME 600 a $IP_ADDRESS" > "$dns_record_file"
+        echo "update add $VM_NAME.${domain_name} 600 a ${domain_controller_ip}" > "$dns_record_file"
         echo "send" >> "$dns_record_file"
         nsupdate -g "$dns_record_file"
     fi
@@ -218,10 +219,13 @@ join_domain()
 # A flag to indicate if this is run from reboot
 RE_ENTER=0
 
-INST_LOG_FILE="/var/log/teradici/agent/install.log"
+if (rpm -q pcoip-agent-graphics); then
+    exit
+fi
+
 if [[ ! -f "$INST_LOG_FILE" ]]
 then
-    mkdir -p "$(dirname ${INST_LOG_FILE})"
+    mkdir -p "$(dirname $${INST_LOG_FILE})"
     touch "$INST_LOG_FILE"
     chmod +644 "$INST_LOG_FILE"
 else
