Separate PCoIP Agent Installation and Registration
PCoIP agent license registration would be skipped if the base image
already have PCoIP agent installed. To fix this, we separate PCoIP
agent installation and registration.

Signed-off-by: Qi Dang <qidang@hp.com>

diff --git a/modules/gcp/centos-gfx/centos-gfx-provisioning.sh.tmpl b/modules/gcp/centos-gfx/centos-gfx-provisioning.sh.tmpl
--- a/modules/gcp/centos-gfx/centos-gfx-provisioning.sh.tmpl
+++ b/modules/gcp/centos-gfx/centos-gfx-provisioning.sh.tmpl
@@ -244,23 +244,19 @@ install_pcoip_agent() {
         exit 1
     fi
     log "--> PCoIP agent installed successfully."
+}
 
+register_pcoip_agent() {
     log "--> Registering PCoIP agent license..."
-    n=0
-    set +x
-    while true; do
-        /usr/sbin/pcoip-register-host --registration-code="$PCOIP_REGISTRATION_CODE" && break
-        n=$[$n+1]
 
-        if [ $n -ge 10 ]; then
-            log "--> ERROR: Failed to register PCoIP agent after $n tries."
-            exit 1
-        fi
-
-        log "--> ERROR: Failed to register PCoIP agent. Retrying in 10s..."
-        sleep 10
-    done
-    set -x
+    retry   10 `# 10 retries` \
+            10 `# 10s interval` \
+            "/usr/sbin/pcoip-register-host --registration-code="$PCOIP_REGISTRATION_CODE" && break" \
+            "--> ERROR: Failed to register PCoIP agent."
+    
+    if [ $? -ne 0 ]; then
+        exit 1
+    fi
     log "--> PCoIP agent registered successfully."
 }
 
@@ -446,6 +442,15 @@ else
     else
         install_pcoip_agent
     fi
+
+    set +x
+    if [[ -z "$PCOIP_REGISTRATION_CODE" ]]
+    then
+        log "--> No PCoIP Registration Code provided. Skipping PCoIP agent registration..."
+    else
+        register_pcoip_agent
+    fi
+    set -x
 
     install_idle_shutdown
 
