AWS: Update CAC module
CAC modules has been updated to work with the --cam-insecure flag, and
the cam deployment service account key is now uploaded to the bucket
from outside of the CAC module to work with CAM Standalone deployments.

Signed-off-by: Sherman Yin <syin@teradici.com>

diff --git a/modules/aws/cac/cac-provisioning.sh.tmpl b/modules/aws/cac/cac-provisioning.sh.tmpl
--- a/modules/aws/cac/cac-provisioning.sh.tmpl
+++ b/modules/aws/cac/cac-provisioning.sh.tmpl
@@ -1,13 +1,14 @@
-#!/bin/bash
-
 # Copyright (c) 2020 Teradici Corporation
 #
 # This source code is licensed under the MIT license found in the
 # LICENSE file in the root directory of this source tree.
 
+#!/bin/bash
+
 LOG_FILE="/var/log/teradici/provisioning.log"
 
 INSTALL_DIR="/root"
+CAC_TOKEN_FILE=$INSTALL_DIR/cac_token
 CAC_INSTALL_LOG="/var/log/teradici/cac-install.log"
 cd $INSTALL_DIR
 
@@ -42,7 +43,31 @@ retry() {
     done
 }
 
+install_prereqs() {
+    log "--> Installing dos2unix, python3..."
+    apt-get -qq update
+    apt install -y dos2unix python3
+
+    if [ $? -ne 0 ]
+    then
+        log "--> ERROR: Failed to install prerequisites. Exiting provisioning script..."
+        exit 1
+    fi
+}
+
 get_credentials() {
+    # In some cases, the CAM Deployment Service Account key is generated by a
+    # new CAM Standalone VM that is being created in parallel as the CAC. Loop
+    # until the file is found in the storage bucket.
+    local timeout=7200
+    local interval=60
+
+    retry $timeout \
+          $interval \
+          "aws s3 cp s3://${bucket_name}/${cam_deployment_sa_file} $INSTALL_DIR" \
+          "--> Downloading CAM Deployment Service Account key from the bucket ${bucket_name}..." \
+          "--> ERROR: Failed to download CAM deployment Service Account key from bucket ${bucket_name}."
+
     # Disable logging of secrets by wrapping the region with set +x and set -x
     set +x
 
@@ -71,8 +96,25 @@ get_credentials() {
 get_cac_token() {
     log "--> Retrieving connector token before CAC install..."
 
+    local args=""
+
+    log "--> Downloading CAM python script from the bucket..."
+    aws s3 cp s3://${bucket_name}/${cam_script} $INSTALL_DIR
+    chmod +x $INSTALL_DIR/${cam_script}
+
+    # Ensure line endings are in Unix format
+    dos2unix $INSTALL_DIR/${cam_script}
+    dos2unix $INSTALL_DIR/${cam_deployment_sa_file}
+
     # Set CAC_TOKEN variable using the script's output
-    CAC_TOKEN=`$INSTALL_DIR/${cam_script} $INSTALL_DIR/${cam_deployment_sa_file} --url ${cam_url}/api/v1`
+    if [ "${cam_insecure}" ]
+    then
+        args="--insecure"
+    fi
+
+    PYTHONWARNINGS="ignore:Unverified HTTPS request" $INSTALL_DIR/${cam_script} $INSTALL_DIR/${cam_deployment_sa_file} --url ${cam_url} --out $CAC_TOKEN_FILE $args
+    CAC_TOKEN=`cat $CAC_TOKEN_FILE`
+    rm $CAC_TOKEN_FILE
 
     # Check and exit provisioning script if retrieving connector token failed
     if [ $? -ne 0 ]; then
@@ -92,12 +134,12 @@ check_required_vars() {
         log "--> ERROR: Missing Active Directory Service Account Password."
         missing_vars="true"
     fi
+    set -x
 
     if [[ -z "$CAC_TOKEN" ]]; then
         log "--> ERROR: Missing Cloud Access Connector Token."
         missing_vars="true"
     fi
-    set -x
 
     if [[ "$missing_vars" = "true" ]]; then
         log "--> Exiting..."
@@ -211,6 +253,7 @@ wait_for_lls() {
 install_cac() {
     log "--> Installing Cloud Access Connector..."
     local retries=10
+    local args=""
 
     log "--> Running command: $INSTALL_DIR/cloud-access-connector install"
     log "--> CAC install options:"
@@ -240,6 +283,12 @@ install_cac() {
     else
         log "  --insecure"
         args=$args"--insecure "
+    fi
+
+    if [ "${cam_insecure}" ]
+    then
+        log "  --cam-insecure"
+        args=$args"--cam-insecure "
     fi
 
     if [ "${lls_ip}" ]
@@ -299,6 +348,8 @@ set -x
 
 # Redirect stdout and stderr to the log file
 exec &>>$LOG_FILE
+
+install_prereqs
 
 get_credentials
 
