AWS: Add cac-cam.py and modify provisioning script
-Added a Python 3 script to create new connector tokens using a
CAM Deployment Service Account.

-Modified the CAC provisioning script to use a CAM Deployment
Service Account and the cac-cam.py script to generate a new
Connector token.

Signed-off-by: Edwin-Pau <epau@teradici.com>

diff --git a/modules/aws/cac/cac-provisioning.sh.tmpl b/modules/aws/cac/cac-provisioning.sh.tmpl
--- a/modules/aws/cac/cac-provisioning.sh.tmpl
+++ b/modules/aws/cac/cac-provisioning.sh.tmpl
@@ -45,28 +45,47 @@ retry() {
 get_credentials() {
     # Disable logging of secrets by wrapping the region with set +x and set -x
     set +x
+    log "--> Downloading CAM credentials JSON file from the bucket..."
+    aws s3 cp s3://${bucket_name}/${cam_deployment_sa_file} $INSTALL_DIR
+
     if [[ -z "${customer_master_key_id}" ]]; then
         log "--> Script is not using encryption for secrets."
 
         PCOIP_REGISTRATION_CODE=${pcoip_registration_code}
         AD_SERVICE_ACCOUNT_PASSWORD=${ad_service_account_password}
-        CAC_TOKEN=${cac_token}
 
     else
         log "--> Script is using encryption key: ${customer_master_key_id}"
-
-        apt install -y awscli
 
         log "--> Decrypting PCoIP registration code..."
         PCOIP_REGISTRATION_CODE=$(aws kms decrypt --region ${aws_region} --ciphertext-blob fileb://<(echo "${pcoip_registration_code}" | base64 -d) --output text --query Plaintext | base64 -d)
         
         log "--> Decrypting AD service account password..."
         AD_SERVICE_ACCOUNT_PASSWORD=$(aws kms decrypt --region ${aws_region} --ciphertext-blob fileb://<(echo "${ad_service_account_password}" | base64 -d) --output text --query Plaintext | base64 -d)
-        
-        log "--> Decrypting CAC token..."
-        CAC_TOKEN=$(aws kms decrypt --region ${aws_region} --ciphertext-blob fileb://<(echo "${cac_token}" | base64 -d) --output text --query Plaintext | base64 -d)
+
+        log "--> Decrypting CAM Deployment Service Account JSON file..."
+        cam_cred_encrypted=$(cat $INSTALL_DIR/${cam_deployment_sa_file})
+        CAM_CREDENTIALS=$(aws kms decrypt --region ${aws_region} --ciphertext-blob fileb://<(echo "$cam_cred_encrypted" | base64 -d) --output text --query Plaintext | base64 -d)
+        echo $CAM_CREDENTIALS | tee $INSTALL_DIR/${cam_deployment_sa_file}
     fi
     set -x
+}
+
+get_cac_token() {
+    log "--> Retrieving connector token before CAC install..."
+
+    log "--> Downloading CAM python script from the bucket..."
+    aws s3 cp s3://${bucket_name}/${cam_script} $INSTALL_DIR
+    chmod +x $INSTALL_DIR/${cam_script}
+
+    # Set CAC_TOKEN variable using the script's output
+    CAC_TOKEN=`$INSTALL_DIR/${cam_script} $INSTALL_DIR/${cam_deployment_sa_file}`
+
+    # Check and exit provisioning script if retrieving connector token failed
+    if [ $? -ne 0 ]; then
+        log "--> ERROR: Failed to retrieve connector token using CAM script. Exiting provisioning script..."
+        exit 1
+    fi
 }
 
 check_required_vars() {
@@ -280,6 +299,8 @@ set -x
 exec &>>$LOG_FILE
 
 get_credentials
+
+get_cac_token
 
 check_required_vars
 
