3/4 GCP: cleanup and refactor CAC startup scripts
Non-functional changes. Cleaned up the style for logging messages so
they are consistent with the rest of the Terraform logging messages.

Refactored each step of this script into separate functions for
better readability.

Signed-off-by: Edwin-Pau <epau@teradici.com>

diff --git a/modules/gcp/cac/cac-startup.sh.tmpl b/modules/gcp/cac/cac-startup.sh.tmpl
--- a/modules/gcp/cac/cac-startup.sh.tmpl
+++ b/modules/gcp/cac/cac-startup.sh.tmpl
@@ -13,6 +13,8 @@ METADATA_BASE_URI="http://metadata.google.internal/computeMetadata/v1/instance"
 METADATA_AUTH_URI="$METADATA_BASE_URI/service-accounts/default/token"
 DECRYPT_URI="https://cloudkms.googleapis.com/v1/${kms_cryptokey_id}:decrypt"
 
+PCOIP_NETWORK_CONF_FILE="/etc/sysctl.d/01-pcoip-cac-network.conf"
+
 export DEBIAN_FRONTEND=noninteractive
 
 log() {
@@ -22,14 +24,14 @@ log() {
 
 get_credentials() {
     if [[ -z "${kms_cryptokey_id}" ]]; then
-        log "Not using encryption"
+        log "--> Script is not using encryption for secrets."
 
         PCOIP_REGISTRATION_CODE=${pcoip_registration_code}
         AD_SERVICE_ACCOUNT_PASSWORD=${ad_service_account_password}
         CAC_TOKEN=${cac_token}
 
     else
-        log "Using encryption key ${kms_cryptokey_id}"
+        log "--> Script is using encryption key: ${kms_cryptokey_id}"
 
         apt-get -qq update
         apt install -y python
@@ -38,156 +40,189 @@ get_credentials() {
         token=$(curl "$METADATA_AUTH_URI" -H "Metadata-Flavor: Google" | python -c "import sys, json; print json.load(sys.stdin)['access_token']")
 
         # Gets data using access token and decodes it
+        log "--> Decrypting PCoIP registration code..."
         data=$(echo "{ \"ciphertext\": \"${pcoip_registration_code}\" }")
         b64_data=$(curl -X POST -d "$data" "$DECRYPT_URI" -H "Authorization: Bearer $token" -H "Content-type: application/json" | python -c "import sys, json; print json.load(sys.stdin)['plaintext']")
         PCOIP_REGISTRATION_CODE=$(echo "$b64_data" | base64 --decode)
 
+        log "--> Decrypting AD service account password..."
         data=$(echo "{ \"ciphertext\": \"${ad_service_account_password}\" }")
         b64_data=$(curl -X POST -d "$data" "$DECRYPT_URI" -H "Authorization: Bearer $token" -H "Content-type: application/json" | python -c "import sys, json; print json.load(sys.stdin)['plaintext']")
         AD_SERVICE_ACCOUNT_PASSWORD=$(echo "$b64_data" | base64 --decode)
 
+        log "--> Decrypting CAC token..."
         data=$(echo "{ \"ciphertext\": \"${cac_token}\" }")
         b64_data=$(curl -X POST -d "$data" "$DECRYPT_URI" -H "Authorization: Bearer $token" -H "Content-type: application/json" | python -c "import sys, json; print json.load(sys.stdin)['plaintext']")
         CAC_TOKEN=$(echo "$b64_data" | base64 --decode)
     fi
+}
 
-    # Exit if any of the required variables are missing
+check_required_vars() {
     if [[ -z "$PCOIP_REGISTRATION_CODE" || -z "$AD_SERVICE_ACCOUNT_PASSWORD" || -z "$CAC_TOKEN" ]]; then
+        log "--> ERROR: Required variables are missing, exiting..."
         exit 1
     fi
 }
 
-if [[ -f "$INSTALL_DIR/cloud-access-connector" ]]; then
-    log "Connector already installed. Skipping startup script."
-    exit 0
-fi
+check_connector_installed() {
+    if [[ -f "$INSTALL_DIR/cloud-access-connector" ]]; then
+        log "--> Connector already installed. Skipping startup script..."
+        exit 0
+    fi
+}
+
+config_network() {
+    if [[ ! -f $PCOIP_NETWORK_CONF_FILE ]]; then
+        log "--> Configuring network..."
+        # Note the indented HEREDOC lines must be preceded by tabs, not spaces
+        cat <<- EOF > $PCOIP_NETWORK_CONF_FILE
+			# System Control network settings for CAC
+			net.core.rmem_max=160000000
+			net.core.rmem_default=160000000
+			net.core.wmem_max=160000000
+			net.core.wmem_default=160000000
+			net.ipv4.udp_mem=120000 240000 600000
+			net.core.netdev_max_backlog=2000
+			EOF
+        
+        sysctl -p $PCOIP_NETWORK_CONF_FILE
+    fi
+}
+
+download_cac() {
+    log "--> Downloading CAC installer..."
+    curl -L ${cac_installer_url} -o $INSTALL_DIR/cloud-access-connector.tar.gz
+    tar xzvf $INSTALL_DIR/cloud-access-connector.tar.gz
+}
+
+install_ldap_utils() {
+    # Wait for service account to be added. Do this last because it takes
+    # a while for new AD user to be added in a new Domain Controller.
+    # Note: using the domain controller IP instead of the domain name for
+    #       the host is more resilient.
+    log "--> Installing ldap_utils..."
+    RETRIES=5
+    while true; do
+        apt-get -qq update
+        apt-get -qq install ldap-utils
+        RC=$?
+        if [ $RC -eq 0 ] || [ $RETRIES -eq 0 ]; then
+            break
+        fi
+
+        log "--> ERROR: Failed to install ldap-utils. $RETRIES retries remaining..."
+        RETRIES=$((RETRIES-1))
+        sleep 5
+    done
+}
+
+wait_for_dc() {
+    log "--> Ensure AD account is available..."
+    TIMEOUT=1200
+    until ldapwhoami \
+        -H ldap://${domain_controller_ip} \
+        -D ${ad_service_account_username}@${domain_name} \
+        -w $AD_SERVICE_ACCOUNT_PASSWORD \
+        -o nettimeout=1; do
+        if [ $TIMEOUT -le 0 ]; then
+            break
+        else
+            log "--> Waiting for AD account ${ad_service_account_username}@${domain_name} to become available. Retrying in 10 seconds... (Timeout in $TIMEOUT seconds)"
+        fi
+        TIMEOUT=$((TIMEOUT-10))
+        sleep 10
+    done
+
+    # Check that the domain name can be resolved and that the LDAP port is accepting
+    # connections. This could have been all done with the ldapwhoami command, but
+    # due to a number of occasional cac-installation issues, such as "domain
+    # controller unreachable" or "DNS error occurred" errors, check these explicitly
+    # for logging and debug purposes.
+    log "--> Ensure domain ${domain_name} can be resolved..."
+    TIMEOUT=1200
+    until host ${domain_name}; do
+        if [ $TIMEOUT -le 0 ]; then
+            break
+        else
+            log "Trying to resolve ${domain_name}. Retrying in 10 seconds... (Timeout in $TIMEOUT seconds)"
+        fi
+        TIMEOUT=$((TIMEOUT-10))
+        sleep 10
+    done
+
+    log "--> Ensure domain ${domain_name} port 636 is reacheable..."
+    TIMEOUT=1200
+    until netcat -vz ${domain_name} 636; do
+        if [ $TIMEOUT -le 0 ]; then
+            break
+        else
+            log "Trying to contact ${domain_name}:636. Retrying in 10 seconds... (Timeout in $TIMEOUT seconds)"
+        fi
+        TIMEOUT=$((TIMEOUT-10))
+        sleep 10
+    done
+}
+
+install_cac() {
+    log "--> Installing Cloud Access Connector..."
+    export CAM_BASE_URI=${cam_url}
+
+    log "--> Running command: $INSTALL_DIR/cloud-access-connector install"
+    log "--> CAC install options:"
+    log "-t $${CAC_TOKEN} --accept-policies"
+    log "--sa-user <ad_service_account_username> --sa-password <ad_service_account_password>"
+    log "--domain ${domain_name} --domain-group ${domain_group}"
+    log "--reg-code $${PCOIP_REGISTRATION_CODE} --sync-interval 5"
+
+    if [ -z "${ssl_key}" ]; then
+        log "--insecure"
+
+        $INSTALL_DIR/cloud-access-connector install \
+            -t $CAC_TOKEN \
+            --accept-policies \
+            --insecure \
+            --sa-user ${ad_service_account_username} \
+            --sa-password "$AD_SERVICE_ACCOUNT_PASSWORD" \
+            --domain ${domain_name} \
+            --domain-group "${domain_group}" \
+            --reg-code $PCOIP_REGISTRATION_CODE \
+            --sync-interval 5 \
+            2>&1 | tee $INSTALL_LOG
+    else
+        gsutil cp gs://${bucket_name}/${ssl_key} $INSTALL_DIR
+        gsutil cp gs://${bucket_name}/${ssl_cert} $INSTALL_DIR
+
+        log "--ssl-key <ssl_key> --ssl-cert <ssl_cert>"
+
+        $INSTALL_DIR/cloud-access-connector install \
+            -t $CAC_TOKEN \
+            --accept-policies \
+            --ssl-key $INSTALL_DIR/${ssl_key} \
+            --ssl-cert $INSTALL_DIR/${ssl_cert} \
+            --sa-user ${ad_service_account_username} \
+            --sa-password "$AD_SERVICE_ACCOUNT_PASSWORD" \
+            --domain ${domain_name} \
+            --domain-group "${domain_group}" \
+            --reg-code $PCOIP_REGISTRATION_CODE \
+            --sync-interval 5 \
+            2>&1 | tee $INSTALL_LOG
+    fi
+}
 
 get_credentials
 
-# Network tuning
-PCOIP_NETWORK_CONF_FILE="/etc/sysctl.d/01-pcoip-cac-network.conf"
+check_required_vars
 
-if [ ! -f $PCOIP_NETWORK_CONF_FILE ]; then
-    # Note the indented HEREDOC lines must be preceded by tabs, not spaces
-    cat <<- EOF > $PCOIP_NETWORK_CONF_FILE
-	# System Control network settings for CAC
-	net.core.rmem_max=160000000
-	net.core.rmem_default=160000000
-	net.core.wmem_max=160000000
-	net.core.wmem_default=160000000
-	net.ipv4.udp_mem=120000 240000 600000
-	net.core.netdev_max_backlog=2000
-	EOF
+check_connector_installed
 
-    sysctl -p $PCOIP_NETWORK_CONF_FILE
-fi
+config_network
 
+download_cac
 
-# download CAC installer
-curl -L ${cac_installer_url} -o $INSTALL_DIR/cloud-access-connector.tar.gz
-tar xzvf $INSTALL_DIR/cloud-access-connector.tar.gz
+install_ldap_utils
 
+wait_for_dc
 
-# Wait for service account to be added
-# do this last because it takes a while for new AD user to be added in a
-# new Domain Controller
-# Note:
-# Using the domain controller IP instead of the domain name for the host is more
-# resilient. With the domain name, sometimes it loops failing to resolve the
-# domain even though another SSH session to the same machine is able to resolve.
-
-echo '### Installing ldap-utils ###'
-RETRIES=5
-while true; do
-    apt-get -qq update
-    apt-get -qq install ldap-utils
-    RC=$?
-    if [ $RC -eq 0 ] || [ $RETRIES -eq 0 ]; then
-        break
-    fi
-
-    echo "Error installing ldap-utils. $RETRIES retries remaining..."
-    RETRIES=$((RETRIES-1))
-    sleep 5
-done
-
-echo '### Ensure AD account is available ###'
-TIMEOUT=1200
-until ldapwhoami \
-    -H ldap://${domain_controller_ip} \
-    -D ${ad_service_account_username}@${domain_name} \
-    -w $AD_SERVICE_ACCOUNT_PASSWORD \
-    -o nettimeout=1; do
-    if [ $TIMEOUT -le 0 ]; then
-        break
-    else
-        echo "Waiting for AD account ${ad_service_account_username}@${domain_name} to become available. Retrying in 10 seconds... (Timeout in $TIMEOUT seconds)"
-    fi
-    TIMEOUT=$((TIMEOUT-10))
-    sleep 10
-done
-
-# Check that the domain name can be resolved and that the LDAP port is accepting
-# connections. This could have been all done with the ldapwhoami command, but
-# due to a number of occasional cac-installation issues, such as "domain
-# controller unreachable" or "DNS error occurred" errors, check these explicitly
-# for logging and debug purposes.
-
-echo '### Ensure domain ${domain_name} can be resolved ###'
-TIMEOUT=1200
-until host ${domain_name}; do
-    if [ $TIMEOUT -le 0 ]; then
-        break
-    else
-        echo "Trying to resolve ${domain_name}. Retrying in 10 seconds... (Timeout in $TIMEOUT seconds)"
-    fi
-    TIMEOUT=$((TIMEOUT-10))
-    sleep 10
-done
-
-echo '### Ensure domain ${domain_name} port 636 is reacheable ###'
-TIMEOUT=1200
-until netcat -vz ${domain_name} 636; do
-    if [ $TIMEOUT -le 0 ]; then
-        break
-    else
-        echo "Trying to contact ${domain_name}:636. Retrying in 10 seconds... (Timeout in $TIMEOUT seconds)"
-    fi
-    TIMEOUT=$((TIMEOUT-10))
-    sleep 10
-done
-
-echo '### Installing Cloud Access Connector ###'
-export CAM_BASE_URI=${cam_url}
-
-if [ -z "${ssl_key}" ]; then
-    $INSTALL_DIR/cloud-access-connector install \
-        -t $CAC_TOKEN \
-        --accept-policies \
-        --insecure \
-        --sa-user ${ad_service_account_username} \
-        --sa-password "$AD_SERVICE_ACCOUNT_PASSWORD" \
-        --domain ${domain_name} \
-        --domain-group "${domain_group}" \
-        --reg-code $PCOIP_REGISTRATION_CODE \
-        --sync-interval 5 \
-        2>&1 | tee -a $INSTALL_LOG
-else
-    gsutil cp gs://${bucket_name}/${ssl_key} $INSTALL_DIR
-    gsutil cp gs://${bucket_name}/${ssl_cert} $INSTALL_DIR
-
-    $INSTALL_DIR/cloud-access-connector install \
-        -t $CAC_TOKEN \
-        --accept-policies \
-        --ssl-key $INSTALL_DIR/${ssl_key} \
-        --ssl-cert $INSTALL_DIR/${ssl_cert} \
-        --sa-user ${ad_service_account_username} \
-        --sa-password "$AD_SERVICE_ACCOUNT_PASSWORD" \
-        --domain ${domain_name} \
-        --domain-group "${domain_group}" \
-        --reg-code $PCOIP_REGISTRATION_CODE \
-        --sync-interval 5 \
-        2>&1 | tee -a $INSTALL_LOG
-fi
+install_cac
 
 docker service ls
